## NFL Predictions Model

2024 Results: https://docs.google.com/presentation/d/1V8nD894wQmctfSbW4x1LnBecPViLVMpCaN5Pzcu_H24/edit?usp=sharing

2025 Results: 
https://docs.google.com/presentation/d/1znbKBgFQ_QQXw_xm91W1x_s_f14T21s4me7ceHXXfXg/edit?usp=sharing

Record over last two seasons (W/L): 389-180-1 (**68.4%**)

Record over last two seasons against Vegas point spreads: 305-257-8 (**54.3%**)

**Important**: .ipynb **MUST** be running in Python version **3.11** or under!

In [1]:
### Changes: Turn fullteamdata columns into functions and 
### use those functions on this_season data. Switch this_season and last_season.
### Change post-thanksgiving to post-midseason
### Also, make everything post-2021 (remove covid year) (get rid of training_x[269:])

In [2]:
!python3 --version

Python 3.11.4


In [3]:
# !pip install nfl_data_py


In [4]:
!pip install pandas
!pip install matplotlib
!pip install nflreadpy
!pip install --upgrade pip

In [5]:
import nfl_data_py as nfl
import pandas as pd
import os
import time
import numpy as np
import urllib.request
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [47]:
import warnings
warnings.filterwarnings("ignore")

In [7]:

#upload nfl_elo data from 2020-2024 - Titled "nfl-win-totals_{insert year here}"
# from google.colab import files
# files.upload()

#VERY IMPORTANT: CHANGE YEAR
# current_year = 2024

from datetime import date, datetime

today = pd.to_datetime(datetime.today())
year = today.year
month = today.month
# day = today.day

current_season = year

if month <= 8:
    current_season = year - 1
elif month == 9:
    first_gameday = pd.to_datetime(nfl.import_schedules([year])['gameday'].head(1))
    if day <= (first_gameday - pd.Timedelta(days=2) + pd.Timedelta(hours=7)):
        current_season = year - 1

current_year = current_season


pbp_data = nfl.import_pbp_data(range(2019, current_year + 1))
# pbp_2022 = nfl.import_pbp_data([2022])
win_totals = nfl.import_schedules(range(2019, current_year + 1))



# pbp_clean_2021 = pbp_2021[(pbp_2021['play_type'] != 'qb_kneel') & (pbp_2021['play_type'] != 'no_play') & (pbp_2021['play_type'] != 'qb_spike')].dropna(subset=['play_type'])
# pbp_rp_2021 = pbp_2021[((pbp_2021['pass'] == 1) | (pbp_2021['rush']==1)) & (pbp_2021['play_type'] != 'no_play')]
# fourthq_2021 = pbp_clean_2021[(pbp_clean_2021['qtr'] == 4) & (abs(pbp_clean_2021['score_differential']) <= 8 )]
# clutch_2021 = fourthq_2021[(fourthq_2021['game_seconds_remaining'] <= 300)]
# drive_2021 = pbp_2021[pbp_2021['drive_play_id_started'] == pbp_2021['play_id']]
# fourth_quarter_drives_2021 = drive_2021[(drive_2021['qtr']==4)&(abs(pbp_clean_2021['score_differential']) <= 8 )]


2019 done.
2020 done.
2021 done.
2022 done.
2023 done.
2024 done.
2025 done.
Downcasting floats.


In [178]:
# clean pbp and win totals data

# filter out all garbage time
garbage_time_bool = (((pbp_data['game_seconds_remaining'] <= 800) & (abs(pbp_data['score_differential']) > 23))
                    | ((pbp_data['game_seconds_remaining'] <= 500) & (abs(pbp_data['score_differential']) > 16))
                    | ((pbp_data['game_seconds_remaining'] <= 120) & (abs(pbp_data['score_differential']) > 8)))
pbp_data = pbp_data[~garbage_time_bool]

# clean win totals
win_totals['away_win'] = win_totals.apply(lambda row : 0 if row['result']>0 else 1, axis=1)
win_totals['home_win'] = win_totals.apply(lambda row : 1 if row['result']>0 else 0, axis=1)

win_totals.replace(to_replace='OAK',value='LV',inplace=True)



In [9]:
###test
# win_totals_2021[win_totals_2021['season']==2022]
seasonal_data = nfl.import_seasonal_data(range(2019, current_year))
depth_chart = nfl.import_depth_charts(range(2019, current_year))
roster = nfl.import_seasonal_rosters(range(2019, current_year + 1))


In [11]:
pbp_data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
0,1.0,2019_01_ATL_MIN,2019090804,MIN,ATL,REG,1,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,36.0,2019_01_ATL_MIN,2019090804,MIN,ATL,REG,1,ATL,away,MIN,...,None,None,None,None,None,None,None,None,None,None
2,51.0,2019_01_ATL_MIN,2019090804,MIN,ATL,REG,1,ATL,away,MIN,...,None,None,None,None,None,None,None,None,None,None
3,79.0,2019_01_ATL_MIN,2019090804,MIN,ATL,REG,1,ATL,away,MIN,...,None,None,None,None,None,None,None,None,None,None
4,100.0,2019_01_ATL_MIN,2019090804,MIN,ATL,REG,1,ATL,away,MIN,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342234,4314.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342235,4302.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Olu Oluwatimi;Jalen Sundell;Anthony Bradford;G...,Christian Barmore;Milton Williams;Cory Durden;...,C;C;G;G;QB;RB;T;T;T;TE;TE,DT;DT;DT;FS;ILB;ILB;ILB;MLB;NT;OLB;OLB,55;61;75;76;14;9;74;67;72;81;88,90;97;94;21;14;48;51;49;95;44;33
342236,4347.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342237,4335.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Olu Oluwatimi;Jalen Sundell;Anthony Bradford;G...,Christian Barmore;Milton Williams;Cory Durden;...,C;C;G;G;QB;RB;T;T;T;TE;TE,DT;DT;DT;FS;ILB;ILB;ILB;MLB;NT;OLB;OLB,55;61;75;76;14;9;74;67;72;81;88,90;97;94;21;14;48;51;49;95;44;33


In [12]:
# check last game of the week

# pbp_data[pbp_data['old_game_id'] == '2025112311']
pbp_data[pbp_data['old_game_id_x'] == sorted(pbp_data['old_game_id_x'].dropna().unique())[-1]]

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
342056,1.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342057,40.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Mike Morris;Brady Russell;Patrick O'Connell;Ty...,Charles Woods;Brenden Schooler;Dell Pettus;Jah...,DE;FB;ILB;ILB;OLB;RB;TE;TE;WR;WR;WR,CB;FS;FS;ILB;ILB;ILB;K;MLB;OLB;OLB;SS,94;38;52;48;57;32;81;18;83;22;19,22;41;24;48;53;15;36;49;33;91;31
342058,57.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Jalen Sundell;Anthony Bradford;Grey Zabel;Sam ...,Carlton Davis III;Christian Gonzalez;Christian...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DT;DT;DT;FS;ILB;ILB;ILB;OLB;SS,61;75;76;14;9;67;72;81;88;10;11,7;0;90;97;94;21;14;48;51;33;31
342059,84.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Jalen Sundell;Anthony Bradford;Grey Zabel;Sam ...,Carlton Davis III;Christian Gonzalez;Christian...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DT;DT;DT;FS;ILB;ILB;ILB;OLB;SS,61;75;76;14;9;67;72;81;88;10;22,7;0;90;97;94;21;14;48;51;33;31
342060,106.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,QUICK OUT,ZONE_COVERAGE,COVER_6,Jalen Sundell;Anthony Bradford;Grey Zabel;Sam ...,Carlton Davis III;Marcus Jones;Christian Gonza...,C;G;G;QB;RB;T;T;TE;WR;WR;WR,CB;CB;CB;DT;DT;DT;FS;ILB;OLB;OLB;SS,61;75;76;14;36;67;72;88;10;22;11,7;25;0;90;97;94;21;14;2;44;31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342234,4314.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342235,4302.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Olu Oluwatimi;Jalen Sundell;Anthony Bradford;G...,Christian Barmore;Milton Williams;Cory Durden;...,C;C;G;G;QB;RB;T;T;T;TE;TE,DT;DT;DT;FS;ILB;ILB;ILB;MLB;NT;OLB;OLB,55;61;75;76;14;9;74;67;72;81;88,90;97;94;21;14;48;51;49;95;44;33
342236,4347.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342237,4335.0,2025_22_SEA_NE,2026020800,NE,SEA,POST,22,SEA,away,NE,...,False,,,None,Olu Oluwatimi;Jalen Sundell;Anthony Bradford;G...,Christian Barmore;Milton Williams;Cory Durden;...,C;C;G;G;QB;RB;T;T;T;TE;TE,DT;DT;DT;FS;ILB;ILB;ILB;MLB;NT;OLB;OLB,55;61;75;76;14;9;74;67;72;81;88,90;97;94;21;14;48;51;49;95;44;33


## Engineering the feature set

### Past season data

In [373]:
###feature engineer training data for previous season


fullteamdata_arr=[]
for i in range(2019,current_year):
  pbp_temp = pbp_data[pbp_data['season']==i]
  # pbp_2022 = nfl.import_pbp_data([2022])
  win_totals_temp = win_totals[win_totals['season']==i]
  if i == 2019:
    win_totals_temp.replace(to_replace='OAK',value='LV',inplace=True)
  pbp_clean = pbp_temp[(pbp_temp['play_type'] != 'qb_kneel') & (pbp_temp['play_type'] != 'no_play') & (pbp_temp['play_type'] != 'qb_spike')].dropna(subset=['play_type'])
  pbp_rp = pbp_temp[((pbp_temp['pass'] == 1) | (pbp_temp['rush']==1)) & (pbp_temp['play_type'] != 'no_play')]
  fourthq = pbp_clean[(pbp_clean['game_seconds_remaining'] <= 1350) & (abs(pbp_clean['score_differential']) <= 16 )]
#   clutch_data = fourthq[(fourthq['game_seconds_remaining'] <= 300)]
  drive_data = pbp_temp[pbp_temp['drive_play_id_started'] == pbp_temp['play_id']]
  fourth_quarter_drives = drive_data[(drive_data['game_seconds_remaining'] <= 1350)&(abs(pbp_clean['score_differential']) <= 16 )]
  #calculate win totals
  home_wins = win_totals_temp.groupby('home_team')['home_win'].sum().reset_index()
  away_wins = win_totals_temp.groupby('away_team')['away_win'].sum().reset_index()
  wins_data = (home_wins['home_win'] + away_wins['away_win']).reset_index()
  wins_data.drop(columns='index', inplace=True)
  wins_data.rename(columns={0:'wins'},inplace=True)
  teams = home_wins[['home_team']].rename(columns={'home_team':'team'})
  wins_data = teams.join(wins_data)

  
#   fourthq = pbp_clean[(pbp_clean['qtr'] == 4) & (abs(pbp_clean['score_differential']) <= 11 )]

  first_down_data = pbp_rp[pbp_rp['down'] == 1]
  second_down_data = pbp_rp[pbp_rp['down'] == 2]
  third_down_data = pbp_rp[(pbp_rp['down'] == 3)]
  fourth_down_data = pbp_rp[pbp_rp['down']==4 ]



  ### post-thanksgiving stats (then changed to post-midseason)
  post_week7_lastseason = pbp_clean[pbp_clean['week']>=7]
  post_week7_lastseason_4q = fourthq[pbp_clean['week']>=7]
  groupby_week7_home = win_totals_temp[win_totals_temp['week']>=7].groupby('home_team')
  groupby_week7_away = win_totals_temp[win_totals_temp['week']>=7].groupby('away_team')
  game_count = groupby_week7_home['week'].nunique()+groupby_week7_away['week'].nunique()

  prefix_postweek7 = 'postweek7_'
  #yards per play(including fourth quarter)
  fullteamdata = post_week7_lastseason.groupby('posteam')['yards_gained'].mean().reset_index().rename(columns={'posteam':'team', 'yards_gained':f'{prefix_postweek7}yards_gained'})
  fullteamdata[f'{prefix_postweek7}ydsperattempt'] = post_week7_lastseason[post_week7_lastseason['pass'] == 1].groupby('posteam')['yards_gained'].mean().reset_index()['yards_gained']
  fullteamdata[f'{prefix_postweek7}ydsperrush'] = post_week7_lastseason[post_week7_lastseason['rush'] == 1].groupby('posteam')['yards_gained'].mean().reset_index()['yards_gained']
  fullteamdata[f'{prefix_postweek7}opp_ydsperplay'] = post_week7_lastseason.groupby('defteam')['yards_gained'].mean().reset_index()['yards_gained']
  fullteamdata[f'{prefix_postweek7}opp_ydsperattempt'] = post_week7_lastseason[post_week7_lastseason['pass'] == 1].groupby('defteam')['yards_gained'].mean().reset_index()['yards_gained']
  fullteamdata[f'{prefix_postweek7}opp_ydsperrush'] = post_week7_lastseason[post_week7_lastseason['rush'] == 1].groupby('defteam')['yards_gained'].mean().reset_index()['yards_gained']
  #4q
  fullteamdata[f'{prefix_postweek7}ydsperplay4q'] = post_week7_lastseason_4q.groupby('posteam')['yards_gained'].mean().reset_index()['yards_gained']
  fullteamdata[f'{prefix_postweek7}opp_ydsperplay4q'] = post_week7_lastseason_4q.groupby('defteam')['yards_gained'].mean().reset_index()['yards_gained']
  #epa and wpa(including 4q)
  fullteamdata[[f'{prefix_postweek7}epa_off',f'{prefix_postweek7}wpa_off']] = post_week7_lastseason.groupby('posteam')[['epa','wpa']].mean().reset_index()[['epa','wpa']]
  fullteamdata[[f'{prefix_postweek7}epa_def',f'{prefix_postweek7}wpa_def']] = def_epa_data = post_week7_lastseason.groupby('defteam')[['epa', 'wpa']].mean().reset_index()[['epa','wpa']]
  fullteamdata[f'{prefix_postweek7}net_epa'] =  fullteamdata[f'{prefix_postweek7}epa_off'] - fullteamdata[f'{prefix_postweek7}epa_def']
  fullteamdata[f'{prefix_postweek7}net_wpa'] =  fullteamdata[f'{prefix_postweek7}wpa_off'] - fullteamdata[f'{prefix_postweek7}wpa_def']
  fullteamdata[[f'{prefix_postweek7}epa_off_4q',f'{prefix_postweek7}wpa_off_4q']] = post_week7_lastseason_4q.groupby("posteam")[['epa', 'wpa']].mean().reset_index()[['epa','wpa']]
  fullteamdata[[f'{prefix_postweek7}epa_def_4q',f'{prefix_postweek7}wpa_def_4q']] = post_week7_lastseason_4q.groupby("defteam")[['epa', 'wpa']].mean().reset_index()[['epa','wpa']]
  #down stats
  postweek7_seconddown = post_week7_lastseason[post_week7_lastseason['down'] == 2]
  postweek7_thirddown = post_week7_lastseason[(post_week7_lastseason['down'] == 3)]
  fullteamdata[f'{prefix_postweek7}2ndydstogo_off'] = postweek7_seconddown.groupby('posteam')['ydstogo'].mean().reset_index()['ydstogo']
  fullteamdata[f'{prefix_postweek7}2ndydstogo_def'] = postweek7_seconddown.groupby('defteam')['ydstogo'].mean().reset_index()['ydstogo']
  fullteamdata[f'{prefix_postweek7}3rdydstogo_off'] = postweek7_thirddown.groupby('posteam')['ydstogo'].mean().reset_index()['ydstogo']
  fullteamdata[f'{prefix_postweek7}3rdydstogo_def'] = postweek7_thirddown.groupby('defteam')['ydstogo'].mean().reset_index()['ydstogo']
  fullteamdata[f'{prefix_postweek7}3rddownconverted_off'] = postweek7_thirddown.groupby('posteam')['third_down_converted'].mean().reset_index()['third_down_converted']
  fullteamdata[f'{prefix_postweek7}3rddownconverted_def'] = postweek7_thirddown.groupby('defteam')['third_down_converted'].mean().reset_index()['third_down_converted']
  #points per game
  fullteamdata[f'{prefix_postweek7}points_pergame_off'] = ((groupby_week7_home['home_score'].sum()+groupby_week7_away['away_score'].sum())/game_count).reset_index()[0]
  fullteamdata[f'{prefix_postweek7}points_pergame_def'] = ((groupby_week7_home['away_score'].sum()+groupby_week7_away['home_score'].sum())/game_count).reset_index()[0]
  #yards per game
  fullteamdata[f'{prefix_postweek7}yards_pergame_off'] = ((post_week7_lastseason.groupby('posteam')['yards_gained'].sum())/game_count).reset_index()[0]
  fullteamdata[f'{prefix_postweek7}yards_pergame_def'] = ((post_week7_lastseason.groupby('defteam')['yards_gained'].sum())/game_count).reset_index()[0]
  #win percentage
  fullteamdata[f'{prefix_postweek7}win_percentage']=((groupby_week7_home['home_win'].sum()+groupby_week7_away['away_win'].sum())/game_count).reset_index()[0]
  #average point differential
  fullteamdata[f'{prefix_postweek7}off_pointdifferential'] = post_week7_lastseason.groupby('posteam')['score_differential'].mean().reset_index()['score_differential']
  fullteamdata[f'{prefix_postweek7}def_pointdifferential'] = (post_week7_lastseason.groupby('defteam')['score_differential'].mean() * (-1)).reset_index()['score_differential']
  #completion percentage
  fullteamdata[f'{prefix_postweek7}off_comp_percentage'] = post_week7_lastseason[post_week7_lastseason['pass'] == 1].groupby('posteam')['complete_pass'].mean().reset_index()['complete_pass']
  fullteamdata[f'{prefix_postweek7}def_comp_percentage'] = post_week7_lastseason[post_week7_lastseason['pass'] == 1].groupby('defteam')['complete_pass'].mean().reset_index()['complete_pass']


  ### account for qb offseason changes
  win_totals_2022 = win_totals[win_totals['season']==i+1]
  seasonal_temp = seasonal_data[seasonal_data['season']==i]
  if i == current_year-1:
    depth_chart_temp = depth_chart[depth_chart['season']==current_year-1]
  else:
    depth_chart_temp = depth_chart[depth_chart['season']==i+1]

  roster_temp = roster[(roster['season']==i)|(roster['season']==i+1)]
  qb1 = depth_chart_temp[(depth_chart_temp['depth_position']=='QB')&(depth_chart_temp['depth_team']=='1')&(depth_chart_temp['week']==1)][['club_code','gsis_id','full_name']]
  qb1 = qb1.drop_duplicates()
  #check for rookies
  qb1_transpose = qb1
  qb1_transpose=qb1_transpose.set_index('club_code')
  qb1_transpose = qb1_transpose.transpose()
  count=0
  for a in qb1_transpose:
    count+=1
    if qb1_transpose.loc['gsis_id',a] not in list(roster[roster['season']==i]['player_id']):
      #set brian hoyer as default
      qb1_transpose[a] = ['00-0026625','Brian Hoyer']
  qb1_transpose=qb1_transpose.transpose()
  qb1_seasonstats = seasonal_temp.set_index('player_id').filter(qb1_transpose['gsis_id'], axis=0)
  qb1.set_index('gsis_id',inplace=True)
  qb1_seasonstats['prev_team'] = qb1['club_code']
  qb1_seasonstats = qb1_seasonstats.reset_index().set_index('prev_team')
  qb1_seasonstats.sort_index(inplace=True)
  qb1_seasonstats = qb1_seasonstats.transpose()
  #fill in default stats
  for b in range(0,32):
    if qb1_seasonstats.iloc[4, b] < 75:
      qb1_seasonstats.iloc[4,b]=90
      qb1_seasonstats.iloc[3,b]=53
      qb1_seasonstats.iloc[5,b]=560
      qb1_seasonstats.iloc[6,b]=5
      qb1_seasonstats.iloc[7,b]=2
      qb1_seasonstats.iloc[15,b]=1.0
  qb1_seasonstats=qb1_seasonstats.transpose()
  ##account for rookies!!!
  #epa/db difference

#   fullteamdata['epa/db_diff'] = ((qb1_seasonstats['passing_epa']/qb1_seasonstats['attempts']) - (pbp_rp[pbp_rp['pass']==1].groupby('posteam')['epa'].mean())).reset_index()[0]
  qb1_seasonstats.reset_index(inplace=True)
  #completion percentage
#   fullteamdata['comppct_diff'] = ((qb1_seasonstats['completions']/qb1_seasonstats['attempts']) - fullteamdata['off_comp_percentage']).reset_index()[0]
  #pass touchdowns minus interceptions
#   fullteamdata['td-int_diff'] = ((qb1_seasonstats['passing_tds']-qb1_seasonstats['interceptions']) - (pbp_rp[pbp_rp['pass']==1].groupby('posteam')['touchdown'].sum()-\
#                                       pbp_rp[pbp_rp['pass']==1].groupby('posteam')['interception'].sum()).reset_index()[0]).reset_index()[0]
  # yards per attempt
#   fullteamdata['ypa_diff'] = ((qb1_seasonstats['passing_yards']/qb1_seasonstats['attempts']) - (pbp_rp[pbp_rp['pass']==1].groupby('posteam')['yards_gained'].mean()).reset_index()['yards_gained']).reset_index()[0]
  #fill in default data for qbs who got few snaps last season

  fullteamdata['wins'] = wins_data['wins']


  fullteamdata_arr.append(fullteamdata)
# fullteamdata
# for i in fullteamdata:
#   i.dropna()
#   print(i.shape)
fullteamdata
# win_totals_2021.groupby('home_team')['week'].nunique() + win_totals_2021.groupby('away_team')['week'].nunique()

,team,postweek7_yards_gained,postweek7_ydsperattempt,postweek7_ydsperrush,postweek7_opp_ydsperplay,postweek7_opp_ydsperattempt,postweek7_opp_ydsperrush,postweek7_ydsperplay4q,postweek7_opp_ydsperplay4q,postweek7_epa_off,...,postweek7_points_pergame_off,postweek7_points_pergame_def,postweek7_yards_pergame_off,postweek7_yards_pergame_def,postweek7_win_percentage,postweek7_off_pointdifferential,postweek7_def_pointdifferential,postweek7_off_comp_percentage,postweek7_def_comp_percentage,wins
0,ARI,4.947771,6.565000,5.011952,4.461030,6.051948,4.455319,4.983936,4.655462,0.101199,...,24.272727,19.636364,353.090909,307.000000,0.545455,-0.202548,1.793923,0.620000,0.589610,8
1,ATL,4.853961,6.873596,4.638365,4.788512,6.501199,4.410138,4.646825,5.090909,-0.000114,...,21.818182,26.181818,356.545455,333.454545,0.363636,-0.977723,1.373368,0.595506,0.606715,8
2,BAL,5.853107,8.278351,5.655172,4.147127,5.866370,3.775194,6.280488,4.389423,0.212992,...,30.307692,19.461538,398.461538,277.538462,0.692308,3.236158,4.366667,0.585052,0.550111,13
3,BUF,5.064646,7.287234,4.488700,4.785794,7.201878,4.025890,4.943662,4.912134,0.180700,...,31.928571,21.857143,358.142857,308.000000,0.785714,1.811111,4.051054,0.593617,0.626761,15
4,CAR,4.195767,5.903485,4.273128,5.100462,6.521628,5.601209,3.935780,4.651515,0.021965,...,21.636364,30.090909,288.363636,401.545455,0.363636,-4.674603,-2.165127,0.525469,0.590331,5
5,CHI,3.689790,4.880196,3.827907,5.458824,7.921965,4.864407,3.837719,5.264151,-0.066762,...,14.727273,24.454545,256.272727,379.636364,0.090909,-7.164921,-5.583006,0.491443,0.595376,5
6,CIN,4.779481,6.538618,3.888372,4.567669,6.466334,4.208000,4.929824,4.777397,0.069398,...,28.636364,25.636364,368.454545,331.363636,0.636364,1.313679,3.839599,0.636179,0.578554,9
7,CLE,4.114634,5.339869,3.995671,4.680662,6.805774,4.145038,3.987069,4.743590,-0.163411,...,14.818182,26.727273,306.727273,334.454545,0.181818,-7.001220,-5.143766,0.531590,0.559055,3
8,DAL,4.177914,5.704261,4.260377,4.819462,6.669173,4.693617,3.917031,5.568807,-0.047944,...,20.363636,27.272727,309.545455,342.181818,0.363636,-1.950920,0.390525,0.578947,0.586466,7
9,DEN,4.598531,6.713604,3.806452,4.550425,6.416667,3.845494,3.880435,4.707692,0.102698,...,26.666667,20.500000,313.083333,312.083333,0.583333,2.144431,3.860267,0.613365,0.574324,10


### The function below is used for feature-engineering rolling window data

In [374]:
# transform function - For mean-level rolling windows
def transform(df_temp, df_this_season = None):
  df_clean = None
  if df_this_season is None:
      df_clean = df_temp[(df_temp['play_type'] != 'qb_kneel') & (df_temp['play_type'] != 'no_play') & (df_temp['play_type'] != 'qb_spike')].dropna(subset=['play_type'])
  else:
    df_clean = pd.concat([df_temp, df_this_season, df_this_season, df_this_season], ignore_index=True)
    df_clean = df_clean[(df_clean['play_type'] != 'qb_kneel') & (df_clean['play_type'] != 'no_play') & (df_clean['play_type'] != 'qb_spike')].dropna(subset=['play_type'])

#     df_clean = df_clean.dropna(axis=1, how='any')
  df = df_clean.groupby('posteam').mean()[['epa','wpa',]].rename(columns={'epa':'off_epa','wpa':'off_wpa'})
  df[['def_epa','def_wpa']] = df_clean.groupby('defteam').mean()[['epa','wpa',]]
  df['epa_net'] = df['off_epa'] - df['def_epa']
  df['wpa_net'] = df['off_wpa'] - df['def_wpa']

  pbp_rp_transform = df_clean[(df_clean['pass']==1)|(df_clean['rush']==1)]
  second_down_transform = df_clean[df_clean['down']==2]
  third_down_transform = df_clean[df_clean['down']==3]
  df[['offrp_epa','offrp_wpa']] = (pbp_rp_transform.groupby('posteam').mean()[['epa','wpa',]])
  df[['defrp_epa','defrp_wpa']] = (pbp_rp_transform.groupby('defteam').mean()[['epa','wpa',]])
  df['epa_rp_net'] = df['offrp_epa'] - df['defrp_epa']
  df['wpa_rp_net'] = df['offrp_wpa'] - df['defrp_wpa']
  df['ydstogo_2nd_off'] = (second_down_transform.groupby('posteam').mean()[['ydstogo']])
  df['ydstogo2nd_def'] = (second_down_transform.groupby('defteam').mean()[['ydstogo']])
  df['ydstogo_3rd_off'] = (third_down_transform.groupby('posteam').mean()[['ydstogo']])
  df['ydstogo_3rd_def'] = (third_down_transform.groupby('defteam').mean()[['ydstogo']])
  df['third_down_off'] = (third_down_transform.groupby('posteam').mean()[['third_down_converted']])
  df['third_down_def'] = (third_down_transform.groupby('defteam').mean()[['third_down_converted']])
  df['ydsperplay'] = (pbp_rp_transform.groupby('posteam').mean()['yards_gained'])
  df['ydsperattempt'] = (pbp_rp_transform[pbp_rp_transform['pass']==1].groupby('posteam').mean()['yards_gained'])
  df['ydsperrush'] = (pbp_rp_transform[pbp_rp_transform['rush']==1].groupby('posteam').mean()['yards_gained'])
  df['opp_ydsperplay'] = (pbp_rp_transform.groupby('defteam').mean()['yards_gained'])
  df['opp_ydsperattempt'] = (pbp_rp_transform[pbp_rp_transform['pass']==1].groupby('defteam').mean()['yards_gained'])
  df['opp_ydsperrush'] = (pbp_rp_transform[pbp_rp_transform['rush']==1].groupby('defteam').mean()['yards_gained'])
  return df

# transform(pbp_2022[(pbp_2022['week']<5)&(pbp_2022['week']>=3)], 'TB','DAL')

# 'TB' not in list(win_totals_2022[win_totals_2022['week']==11]['away_team']) and \
#       'TB' not in list(win_totals_2022[win_totals_2022['week']==11]['home_team'])

### Feature-engineering for season-to-date data

In [375]:
### thisseason method - Current season-to-date features

def thisseason(pbp_temp: pd.DataFrame, schedule_temp: pd.DataFrame) -> pd.DataFrame:
    """
    Build the same team-level features as the 'previous season' block,
    but using the current season games available in pbp_temp and schedule_temp.

    Returns a DataFrame indexed by team with columns suffixed '_thisyear'.
    """

    # ---------- helpers ----------
    def safe_div(num: pd.Series, den: pd.Series) -> pd.Series:
        den = den.replace(0, np.nan)
        return num / den

    def by_team_mean(df: pd.DataFrame, team_col: str, cols) -> pd.DataFrame:
        return df.groupby(team_col)[cols].mean()

    def by_team_sum(df: pd.DataFrame, team_col: str, cols) -> pd.DataFrame:
        return df.groupby(team_col)[cols].sum()

    def by_team_count(df: pd.DataFrame, team_col: str, col_to_count: str) -> pd.Series:
        return df.groupby(team_col)[col_to_count].count()

    # ---------- clean pbp ----------
    df_clean = pbp_temp[
        (pbp_temp["play_type"] != "qb_kneel")
        & (pbp_temp["play_type"] != "no_play")
        & (pbp_temp["play_type"] != "qb_spike")
    ].dropna(subset=["play_type"]).copy()

    pbp_rp = df_clean[(df_clean["pass"] == 1) | (df_clean["rush"] == 1)].copy()

    clutch = df_clean[(df_clean["game_seconds_remaining"] <= 1350) & (df_clean["score_differential"].abs() <= 16)].copy()

    # Drives: start-of-drive rows only
    drive_data = pbp_temp[pbp_temp["drive_play_id_started"] == pbp_temp["play_id"]].copy()
    clutch_drives = drive_data[(drive_data["game_seconds_remaining"] <= 1350) & (drive_data["score_differential"].abs() <= 16)].copy()

    # ---------- schedule prep ----------
    sched = schedule_temp.copy()

    # if schedule_temp doesn't already have home_win/away_win like your historical win_totals,
    # compute them from result (home_score - away_score) convention used in your code.
    if "home_win" not in sched.columns or "away_win" not in sched.columns:
        # note: ties -> home_win=0, away_win=0 (matches your lambda behavior for result==0)
        sched["home_win"] = (sched["result"] > 0).astype(int)
        sched["away_win"] = (sched["result"] < 0).astype(int)

    # team universe for stable alignment
    teams = pd.Index(
        pd.unique(pd.concat([sched["home_team"], sched["away_team"]], ignore_index=True)),
        name="team",
    )

    # games played per team (home + away unique weeks)
    groupby_home = sched.groupby("home_team")
    groupby_away = sched.groupby("away_team")
    game_count_data = (groupby_home["week"].nunique() + groupby_away["week"].nunique()).reindex(teams)

    # one-score and reg splits if present
    one_score = sched[sched["result"].abs() <= 8].copy()
    has_game_type = "game_type" in sched.columns
    reg = sched[sched["game_type"] == "REG"].copy() if has_game_type else None

    reg_game_count_data = None
    if has_game_type:
        reg_home = reg.groupby("home_team")["week"].nunique()
        reg_away = reg.groupby("away_team")["week"].nunique()
        reg_game_count_data = (reg_home + reg_away).reindex(teams)

    # wins + win %
    wins = (groupby_home["home_win"].sum() + groupby_away["away_win"].sum()).reindex(teams)
    win_percentage = safe_div(wins, game_count_data)

    # point differential from schedule
    pointdiff = (groupby_home["result"].sum() + (groupby_away["result"].sum() * -1)).reindex(teams)
#     onescore_pointdiff = (
#         one_score.groupby("home_team")["result"].sum()
#         + (one_score.groupby("away_team")["result"].sum() * -1)
#     ).reindex(teams)

    # avg spread line (home - away, like your code)
    avg_spreadline = (groupby_home["spread_line"].mean() - groupby_away["spread_line"].mean()).reindex(teams)

    # points per game (off/def), plus reg variants if possible
    points_off = safe_div((groupby_home["home_score"].sum() + groupby_away["away_score"].sum()).reindex(teams), game_count_data)
    points_def = safe_div((groupby_home["away_score"].sum() + groupby_away["home_score"].sum()).reindex(teams), game_count_data)

    points_off_reg = pd.Series(index=teams, dtype="float64")
    points_def_reg = pd.Series(index=teams, dtype="float64")
    if has_game_type and reg_game_count_data is not None:
        reg_home_g = reg.groupby("home_team")
        reg_away_g = reg.groupby("away_team")
        points_off_reg = safe_div((reg_home_g["home_score"].sum() + reg_away_g["away_score"].sum()).reindex(teams), reg_game_count_data)
        points_def_reg = safe_div((reg_home_g["away_score"].sum() + reg_away_g["home_score"].sum()).reindex(teams), reg_game_count_data)

    # ---------- start building fullteamdata-like table ----------
    df = pd.DataFrame(index=teams)

    # off/def epa+wpa
    off_epa = by_team_mean(df_clean, "posteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "off_epa", "wpa": "off_wpa"})
    def_epa = by_team_mean(df_clean, "defteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "def_epa", "wpa": "def_wpa"})
    df = df.join(off_epa).join(def_epa)
    df['net_epa'] = df['off_epa'] - df['def_epa']
    df['net_wpa'] = df['off_wpa'] - df['def_wpa']
    # run/pass epa+wpa
    off_rp = by_team_mean(pbp_rp, "posteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "offrp_epa", "wpa": "offrp_wpa"})
    def_rp = by_team_mean(pbp_rp, "defteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "defrp_epa", "wpa": "defrp_wpa"})
    df = df.join(off_rp).join(def_rp)
    df['net_rp_epa'] = df['offrp_epa'] - df['defrp_epa']
    df['net_rp_wpa'] = df['offrp_wpa'] - df['defrp_wpa']
    # 4Q close-game epa+wpa
    off_4q = by_team_mean(clutch, "posteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "off4q_epa", "wpa": "off4q_wpa"})
    def_4q = by_team_mean(clutch, "defteam", ["epa", "wpa"]).reindex(teams).rename(columns={"epa": "def4q_epa", "wpa": "def4q_wpa"})
    df = df.join(off_4q).join(def_4q)

    # downs subsets
    first_down_data = pbp_rp[pbp_rp["down"] == 1]
    second_down_data = pbp_rp[pbp_rp["down"] == 2]
    third_down_data = pbp_rp[pbp_rp["down"] == 3]
    fourth_down_data = pbp_rp[pbp_rp["down"] == 4]

    # ydstogo 2nd/3rd
    df["ydstogo_2nd_off"] = second_down_data.groupby("posteam")["ydstogo"].mean().reindex(teams)
    df["ydstogo_2nd_def"] = second_down_data.groupby("defteam")["ydstogo"].mean().reindex(teams)
    df['net_ydstogo_2nd'] = df['ydstogo_2nd_def'] - df['ydstogo_2nd_off']
    df["ydstogo_3rd_off"] = third_down_data.groupby("posteam")["ydstogo"].mean().reindex(teams)
    df["ydstogo_3rd_def"] = third_down_data.groupby("defteam")["ydstogo"].mean().reindex(teams)
    df['net_ydstogo_3rd'] = df['ydstogo_3rd_def'] - df['ydstogo_3rd_off']

    # 3rd/4th down conversion
    df["third_down_off"] = third_down_data.groupby("posteam")["third_down_converted"].mean().reindex(teams)
    df["third_down_def"] = third_down_data.groupby("defteam")["third_down_converted"].mean().reindex(teams)
    df['net_third_down'] = df['third_down_off'] - df['third_down_def']
    df["fourth_down_off"] = fourth_down_data.groupby("posteam")["fourth_down_converted"].mean().reindex(teams)
    df["fourth_down_def"] = fourth_down_data.groupby("defteam")["fourth_down_converted"].mean().reindex(teams)
    df['net_fourth_down'] = df['fourth_down_off'] - df['fourth_down_def']
    # 4Q close 3rd down conversion (your code used abs(score_differential)<=8 on 4Q)
    third_down_4q = third_down_data[(third_down_data["game_seconds_remaining"] <= 1350) & (third_down_data["score_differential"].abs() <= 16)]
    df["third_down_off_4q"] = third_down_4q.groupby("posteam")["third_down_converted"].mean().reindex(teams)
    df["third_down_def_4q"] = third_down_4q.groupby("defteam")["third_down_converted"].mean().reindex(teams)

    # first down pass/run ratios
    fd_pass = first_down_data.groupby("posteam")["pass"].sum().reindex(teams)
    fd_rush = first_down_data.groupby("posteam")["rush"].sum().reindex(teams)
    df["first_down_passrun_off"] = safe_div(fd_pass, fd_rush)

    fd_pass_def = first_down_data.groupby("defteam")["pass"].sum().reindex(teams)
    fd_rush_def = first_down_data.groupby("defteam")["rush"].sum().reindex(teams)
    df["first_down_passrun_def"] = safe_div(fd_pass_def, fd_rush_def)
    df['net_firstdown_passrun'] = df['first_down_passrun_off'] - df['first_down_passrun_def']

    # basic play-type stats
#     df["total_punt"] = pbp_temp[pbp_temp["play_type"] == "punt"].groupby("posteam")["play_id"].count().reindex(teams)
    df["goal_to_go"] = df_clean.groupby("posteam")["goal_to_go"].mean().reindex(teams)
    df["goal_to_go_def"] = df_clean.groupby("defteam")["goal_to_go"].mean().reindex(teams)

#     df["kickoff"] = df_clean[df_clean["play_type"] == "kickoff"].groupby("defteam")["play_id"].count().reindex(teams)
#     df["kickoff_received"] = df_clean[df_clean["play_type"] == "kickoff"].groupby("posteam")["play_id"].count().reindex(teams)

    # pass/run ratio (overall) and opponent (note: your historical code had a likely typo for opp ratio denom;
    # here we use defteam pass / defteam rush as the natural mirror.)
    pass_sum_off = pbp_rp.groupby("posteam")["pass"].sum().reindex(teams)
    rush_sum_off = pbp_rp.groupby("posteam")["rush"].sum().reindex(teams)
    df["pass_run_ratio"] = safe_div(pass_sum_off, rush_sum_off)

    pass_sum_def = pbp_rp.groupby("defteam")["pass"].sum().reindex(teams)
    rush_sum_def = pbp_rp.groupby("defteam")["rush"].sum().reindex(teams)
    df["opp_pass_run_ratio"] = safe_div(pass_sum_def, rush_sum_def)

    # play counts + differential
    playcount_off = df_clean["posteam"].value_counts().reindex(teams)
    playcount_def = df_clean["defteam"].value_counts().reindex(teams)
    df["playcount"] = playcount_off
    df["play_differential"] = (playcount_off - playcount_def)

    # yards per play / attempt / rush (off and def), plus 4Q close versions
    df["ydsperplay"] = pbp_rp.groupby("posteam")["yards_gained"].mean().reindex(teams)
    df["ydsperattempt"] = pbp_rp[pbp_rp["pass"] == 1].groupby("posteam")["yards_gained"].mean().reindex(teams)
    df["ydsperrush"] = pbp_rp[pbp_rp["rush"] == 1].groupby("posteam")["yards_gained"].mean().reindex(teams)

    df["opp_ydsperplay"] = pbp_rp.groupby("defteam")["yards_gained"].mean().reindex(teams)
    df["opp_ydsperattempt"] = pbp_rp[pbp_rp["pass"] == 1].groupby("defteam")["yards_gained"].mean().reindex(teams)
    df["opp_ydsperrush"] = pbp_rp[pbp_rp["rush"] == 1].groupby("defteam")["yards_gained"].mean().reindex(teams)
  
    df['net_ydsperplay'] = df['ydsperplay'] - df['opp_ydsperplay']
    df['net_ydsperattempt'] = df['ydsperattempt'] - df['opp_ydsperattempt']
    df['net_ydsperrush'] = df['ydsperrush'] - df['opp_ydsperrush']

#     df["ydsperplay4q"] = clutch.groupby("posteam")["yards_gained"].mean().reindex(teams)
#     df["ydsperattempt4q"] = clutch[clutch["pass"] == 1].groupby("posteam")["yards_gained"].mean().reindex(teams)
#     df["ydsperrush4q"] = clutch[clutch["rush"] == 1].groupby("posteam")["yards_gained"].mean().reindex(teams)

#     df["opp_ydsperplay4q"] = clutch.groupby("defteam")["yards_gained"].mean().reindex(teams)
#     df["opp_ydsperattempt4q"] = clutch[clutch["pass"] == 1].groupby("defteam")["yards_gained"].mean().reindex(teams)
#     df["opp_ydsperrush4q"] = clutch[clutch["rush"] == 1].groupby("defteam")["yards_gained"].mean().reindex(teams)

    # YAC
    df["off_YAC"] = pbp_rp.groupby("posteam")["yards_after_catch"].mean().reindex(teams)
    df["def_YAC"] = pbp_rp.groupby("defteam")["yards_after_catch"].mean().reindex(teams)

    df['net_YAC'] = df["off_YAC"] - df["def_YAC"]
    
    # point differential from pbp (incl 4Q close versions)
    df["off_pointdifferential"] = df_clean.groupby("posteam")["score_differential"].mean().reindex(teams)
    df["def_pointdifferential"] = (df_clean.groupby("defteam")["score_differential"].mean() * (-1)).reindex(teams)
#     df["off_pointdifferential_4q"] = clutch.groupby("posteam")["score_differential"].mean().reindex(teams)
#     df["def_pointdifferential_4q"] = (clutch.groupby("defteam")["score_differential"].mean() * (-1)).reindex(teams)

    # completion %
    df["off_comp_percentage"] = pbp_rp[pbp_rp["pass"] == 1].groupby("posteam")["complete_pass"].mean().reindex(teams)
    df["def_comp_percentage"] = pbp_rp[pbp_rp["pass"] == 1].groupby("defteam")["complete_pass"].mean().reindex(teams)
    df['net_comppct'] = df['off_comp_percentage'] - df['def_comp_percentage']
    
    
#     df["off_comp_percentage_4q"] = clutch[clutch["pass"] == 1].groupby("posteam")["complete_pass"].mean().reindex(teams)
#     df["def_comp_percentage_4q"] = clutch[clutch["pass"] == 1].groupby("defteam")["complete_pass"].mean().reindex(teams)

    # interception rates
    df["off_interception_rate"] = pbp_rp[pbp_rp["pass"] == 1].groupby("posteam")["interception"].mean().reindex(teams)
    df["def_interception_rate"] = pbp_rp[pbp_rp["pass"] == 1].groupby("defteam")["interception"].mean().reindex(teams)
    df['net_int_rate'] = df['def_interception_rate'] - df['off_interception_rate']
    
    
#     df["off_interception_rate_4q"] = clutch[clutch["pass"] == 1].groupby("posteam")["interception"].mean().reindex(teams)
#     df["def_interception_rate_4q"] = clutch[clutch["pass"] == 1].groupby("defteam")["interception"].mean().reindex(teams)

    # fumbles
    df["off_fumble"] = df_clean.groupby("posteam")["fumble"].mean().reindex(teams)
    df["off_fumble_lost"] = df_clean.groupby("posteam")["fumble_lost"].mean().reindex(teams)
    df["def_fumble_lost"] = df_clean.groupby("defteam")["fumble_lost"].mean().reindex(teams)
    df["fumble_forced"] = df_clean.groupby("defteam")["fumble_forced"].mean().reindex(teams)

    # touchdowns and rates
#     td_off_sum = df_clean.groupby("posteam")["touchdown"].sum().reindex(teams)
#     td_def_sum = df_clean.groupby("defteam")["touchdown"].sum().reindex(teams)
#     df["touchdown_diff"] = (td_off_sum - td_def_sum)

#     td_off_sum_4q = clutch.groupby("posteam")["touchdown"].sum().reindex(teams)
#     td_def_sum_4q = clutch.groupby("defteam")["touchdown"].sum().reindex(teams)
#     df["touchdown_diff_4q"] = (td_off_sum_4q - td_def_sum_4q)

    df["touchdownrate_off"] = df_clean.groupby("posteam")["touchdown"].mean().reindex(teams)
    df["touchdownrate_def"] = df_clean.groupby("defteam")["touchdown"].mean().reindex(teams)
    df['net_touchdown_rate'] = df['touchdownrate_off'] - df['touchdownrate_def']


    # sacks (diff + rates)
#     sack_def_sum = df_clean.groupby("defteam")["sack"].sum().reindex(teams)
#     sack_off_sum = df_clean.groupby("posteam")["sack"].sum().reindex(teams)
#     df["sack_diff"] = (sack_def_sum - sack_off_sum)

#     sack_def_sum_4q = clutch.groupby("defteam")["sack"].sum().reindex(teams)
#     sack_off_sum_4q = clutch.groupby("posteam")["sack"].sum().reindex(teams)
#     df["sack_diff4q"] = (sack_def_sum_4q - sack_off_sum_4q)

    df["sack_rate_pbp"] = pbp_rp.groupby("defteam")["sack"].mean().reindex(teams)
    df["sackrate_def"] = pbp_rp[pbp_rp["pass"] == 1].groupby("defteam")["sack"].mean().reindex(teams)
    df["sackrate_off"] = pbp_rp[pbp_rp["pass"] == 1].groupby("posteam")["sack"].mean().reindex(teams)
    df['net_sack_rate'] = df['sackrate_def'] - df['sackrate_off']
    

    # QB hits (diff + rates)
#     qbhit_def_sum = df_clean.groupby("defteam")["qb_hit"].sum().reindex(teams)
#     qbhit_off_sum = df_clean.groupby("posteam")["qb_hit"].sum().reindex(teams)
#     df["qbhit_diff"] = (qbhit_def_sum - qbhit_off_sum)

#     qbhit_def_sum_4q = clutch.groupby("defteam")["qb_hit"].sum().reindex(teams)
#     qbhit_off_sum_4q = clutch.groupby("posteam")["qb_hit"].sum().reindex(teams)
#     df["qbhit_diff4q"] = (qbhit_def_sum_4q - qbhit_off_sum_4q)

    df["qbhit_rate_pbp"] = pbp_rp.groupby("defteam")["qb_hit"].mean().reindex(teams)
    df["qbhitrate_def"] = pbp_rp[pbp_rp["pass"] == 1].groupby("defteam")["qb_hit"].mean().reindex(teams)
    df["qbhitrate_off"] = pbp_rp[pbp_rp["pass"] == 1].groupby("posteam")["qb_hit"].mean().reindex(teams)
    df['net_qbhitrate'] = df['qbhitrate_def'] - df['qbhitrate_off']

    
    # win probability + series success
    df["off_winprob"] = df_clean.groupby("posteam")["wp"].mean().reindex(teams)
    df["def_winprob"] = df_clean.groupby("defteam")["def_wp"].mean().reindex(teams)
    df["off_winprob_fourthq"] = clutch.groupby("posteam")["wp"].mean().reindex(teams)
    df["def_winprob_fourthq"] = clutch.groupby("defteam")["def_wp"].mean().reindex(teams)

    df["off_series_success"] = df_clean.groupby("posteam")["series_success"].mean().reindex(teams)
    df["def_series_success"] = df_clean.groupby("defteam")["series_success"].mean().reindex(teams)
    df['net_series_success'] = df['off_series_success'] - df['def_series_success']

    df["off_series_success_fourthq"] = clutch.groupby("posteam")["series_success"].mean().reindex(teams)
    df["def_series_success_fourthq"] = clutch.groupby("defteam")["series_success"].mean().reindex(teams)

#     first down diffs / rates
    fd_off_sum = df_clean.groupby("posteam")["first_down"].sum().reindex(teams)
    fd_def_sum = df_clean.groupby("defteam")["first_down"].sum().reindex(teams)
#     df["firstdown_diff"] = (fd_off_sum - fd_def_sum)

    df["firstdownrate_off"] = df_clean.groupby("posteam")["first_down"].mean().reindex(teams)
    df["firstdownrate_def"] = df_clean.groupby("defteam")["first_down"].mean().reindex(teams)
    df['net_firstdownrate'] = df['firstdownrate_off'] - df['firstdownrate_def']

    
    df["firstdownrate_diff4q"] = (clutch.groupby("posteam")["first_down"].mean() - clutch.groupby("defteam")["first_down"].mean()).reindex(teams)

    # red zone (drive-based)
    # numerator: drives inside20 that ended TD; denominator: drives inside20 count
    rz_num_off = drive_data[(drive_data["drive_inside20"] == 1) & (drive_data["fixed_drive_result"] == "Touchdown")].groupby("posteam")["play_id"].count().reindex(teams)
    rz_den_off = drive_data.groupby("posteam")["drive_inside20"].sum().reindex(teams)
    df["red_zone_off"] = safe_div(rz_num_off, rz_den_off)

    rz_num_def = drive_data[(drive_data["drive_inside20"] == 1) & (drive_data["fixed_drive_result"] == "Touchdown")].groupby("defteam")["play_id"].count().reindex(teams)
    rz_den_def = drive_data.groupby("defteam")["drive_inside20"].sum().reindex(teams)
    df["red_zone_def"] = safe_div(rz_num_def, rz_den_def)
    df['net_redzone'] = df['red_zone_off'] - df['red_zone_def']


    # goal-to-go series success (pbp-based)
    gtg = df_clean[df_clean["goal_to_go"] == 1]
#     df["goaltogo_off"] = gtg.groupby("posteam")["series_success"].mean().reindex(teams)
#     df["goaltogo_def"] = gtg.groupby("defteam")["series_success"].mean().reindex(teams)
#     df['net_goaltogo'] = df['goaltogo_off'] - df['goaltogo_def']


    # field position + field goals
    drive_nokickoff = drive_data[drive_data["play_type"] != "kickoff"]
    df["drive_avgstart_off"] = drive_nokickoff.groupby("posteam")["yardline_100"].mean().reindex(teams)
    df["drive_avgstart_def"] = drive_nokickoff.groupby("defteam")["yardline_100"].mean().reindex(teams)
    df['net_avgstart'] = df['drive_avgstart_off'] - df['drive_avgstart_def']


    df["avg_fieldpos_off"] = df_clean.groupby("posteam")["yardline_100"].mean().reindex(teams)
    df["avg_fieldpos_def"] = df_clean.groupby("defteam")["yardline_100"].mean().reindex(teams)
    df['net_avgfieldpos'] = df['avg_fieldpos_off'] - df['avg_fieldpos_def']


    fg_num = drive_data[drive_data["fixed_drive_result"] == "Field goal"].groupby("posteam")["play_id"].count().reindex(teams)
    fg_den = df_clean.groupby("posteam")["field_goal_attempt"].sum().reindex(teams)
    df["field_goal"] = safe_div(fg_num, fg_den)

#     # penalties (team committing the penalty)
#     if "penalty_team" in pbp_temp.columns:
#         df["penalties"] = pbp_temp.groupby("penalty_team")["play_id"].count().reindex(teams)
#         if "penalty_yards" in pbp_temp.columns:
#             df["penalty_yards"] = pbp_temp.groupby("penalty_team")["penalty_yards"].sum().reindex(teams)

#         bigdowns = pbp_temp[(pbp_temp["down"] == 3) | (pbp_temp["down"] == 4)]
#         df["penalties_bigdowns"] = bigdowns.groupby("penalty_team")["play_id"].count().reindex(teams)
#         if "penalty_yards" in pbp_temp.columns:
#             df["penaltyyards_bigdowns"] = bigdowns.groupby("penalty_team")["penalty_yards"].sum().reindex(teams)
#     else:
#         df["penalties"] = np.nan
#         df["penalty_yards"] = np.nan
#         df["penalties_bigdowns"] = np.nan
#         df["penaltyyards_bigdowns"] = np.nan

    # per-drive data
    off_drive_count = drive_data.groupby("posteam")["play_id"].count().reindex(teams)
    def_drive_count = drive_data.groupby("defteam")["play_id"].count().reindex(teams)

    off_drive_count_4q = clutch_drives.groupby("posteam")["play_id"].count().reindex(teams)
    def_drive_count_4q = clutch_drives.groupby("defteam")["play_id"].count().reindex(teams)

    df["drive_count"] = off_drive_count

    drive_off_means = drive_data.groupby("posteam")[["drive_play_count", "drive_first_downs", "drive_inside20", "drive_ended_with_score"]].mean().reindex(teams)
    drive_def_means = drive_data.groupby("defteam")[["drive_play_count", "drive_first_downs", "drive_inside20", "drive_ended_with_score"]].mean().reindex(teams)

    df[["off_plays_perdrive", "off_firstdowns_perdrive", "off_drive_inside20", "off_drive_endedwithscore"]] = drive_off_means
    df[["def_plays_perdrive", "def_firstdowns_perdrive", "def_drive_inside20", "def_drive_endedwithscore"]] = drive_def_means
    df['net_plays_perdrive'] = df['off_plays_perdrive'] - df['def_plays_perdrive']
    df['net_firstdowns_perdrive'] = df['off_firstdowns_perdrive'] - df['def_firstdowns_perdrive']
    df['net_offdriveinside20'] = df['off_drive_inside20'] - df['def_drive_inside20']
    df['net_drive_endedwithscore'] = df['off_drive_endedwithscore'] - df['def_drive_endedwithscore']

    
    drive_off_means_4q = clutch_drives.groupby("posteam")[["drive_play_count", "drive_first_downs", "drive_inside20", "drive_ended_with_score"]].mean().reindex(teams)
    drive_def_means_4q = clutch_drives.groupby("defteam")[["drive_play_count", "drive_first_downs", "drive_inside20", "drive_ended_with_score"]].mean().reindex(teams)

#     df[["off_plays_perdrive_4q", "off_firstdowns_perdrive_4q", "off_drive_inside20_4q", "off_drive_endedwithscore_4q"]] = drive_off_means_4q
#     df[["def_plays_perdrive_4q", "def_firstdowns_perdrive_4q", "def_drive_inside20_4q", "def_drive_endedwithscore_4q"]] = drive_def_means_4q

    # yards per drive
    off_yards = df_clean.groupby("posteam")["yards_gained"].sum().reindex(teams)
    def_yards = df_clean.groupby("defteam")["yards_gained"].sum().reindex(teams)

    off_yards_4q = clutch.groupby("posteam")["yards_gained"].sum().reindex(teams)
    def_yards_4q = clutch.groupby("defteam")["yards_gained"].sum().reindex(teams)

    df["off_yards_per_drive"] = safe_div(off_yards, off_drive_count)
    df["def_yards_per_drive"] = safe_div(def_yards, def_drive_count)
    df['net_yards_per_drive'] = df['off_yards_per_drive'] - df['def_yards_per_drive']

#     df["off_yards_per_drive_4q"] = safe_div(off_yards_4q, off_drive_count_4q)
#     df["def_yards_per_drive4q"] = safe_div(def_yards_4q, def_drive_count_4q)

    # touchdowns per drive
    off_td = df_clean.groupby("posteam")["touchdown"].sum().reindex(teams)
    def_td = df_clean.groupby("defteam")["touchdown"].sum().reindex(teams)
#     off_td_4q = clutch.groupby("posteam")["touchdown"].sum().reindex(teams)
#     def_td_4q = clutch.groupby("defteam")["touchdown"].sum().reindex(teams)

    df["off_touchdowns_perdrive"] = safe_div(off_td, off_drive_count)
    df["def_touchdowns_perdrive"] = safe_div(def_td, def_drive_count)
    df['net_touchdowns_per_drive'] = df['off_touchdowns_perdrive'] - df['def_touchdowns_perdrive']

#     df["off_touchdowns_perdrive_4q"] = safe_div(off_td_4q, off_drive_count_4q)
#     df["def_touchdowns_perdrive_4q"] = safe_div(def_td_4q, def_drive_count_4q)

    # bad drives per drive (not TD or FG)
    bad_off = drive_data[(drive_data["fixed_drive_result"] != "Touchdown") & (drive_data["fixed_drive_result"] != "Field Goal")].groupby("posteam")["play_id"].count().reindex(teams)
    bad_def = drive_data[(drive_data["fixed_drive_result"] != "Touchdown") & (drive_data["fixed_drive_result"] != "Field Goal")].groupby("defteam")["play_id"].count().reindex(teams)
    bad_off_4q = clutch_drives[(clutch_drives["fixed_drive_result"] != "Touchdown") & (clutch_drives["fixed_drive_result"] != "Field Goal")].groupby("posteam")["play_id"].count().reindex(teams)
    bad_def_4q = clutch_drives[(clutch_drives["fixed_drive_result"] != "Touchdown") & (clutch_drives["fixed_drive_result"] != "Field Goal")].groupby("defteam")["play_id"].count().reindex(teams)

    df["off_bad_drives_perdrive"] = safe_div(bad_off, off_drive_count)
    df["def_bad_drives_perdrive"] = safe_div(bad_def, def_drive_count)
    df['net_bad_drives_perdrive'] = df['def_bad_drives_perdrive'] - df['off_bad_drives_perdrive']

#     df["off_bad_drives_perdrive_4q"] = safe_div(bad_off_4q, off_drive_count_4q)
#     df["def_bad_drives_perdrive_4q"] = safe_div(bad_def_4q, def_drive_count_4q)

    # seasonal per-game stats from schedule and pbp
    df["wins"] = wins
    df["win_percentage"] = win_percentage
    df["pointdifferential"] = pointdiff
#     df["pointdifferential_onescore"] = onescore_pointdiff
    df["avg_spreadline"] = avg_spreadline

    df["points_pergame_off"] = points_off
    df["points_pergame_def"] = points_def
    df["points_pergame_off_reg"] = points_off_reg
    df["points_pergame_def_reg"] = points_def_reg

    df["yds_pergame_off"] = safe_div(off_yards, game_count_data)
    df["yds_pergame_def"] = safe_div(def_yards, game_count_data)
    df['net_yds_pergame'] = df['yds_pergame_off'] - df['yds_pergame_def']


#     # reg yds per game if available
#     if has_game_type and reg_game_count_data is not None:
#         df_clean_reg = df_clean[df_clean.get("season_type", "REG") == "REG"] if "season_type" in df_clean.columns else df_clean
#         off_yards_reg = df_clean_reg.groupby("posteam")["yards_gained"].sum().reindex(teams)
#         def_yards_reg = df_clean_reg.groupby("defteam")["yards_gained"].sum().reindex(teams)
#         df["yds_pergame_off_reg"] = safe_div(off_yards_reg, reg_game_count_data)
#         df["yds_pergame_def_reg"] = safe_div(def_yards_reg, reg_game_count_data)
#     else:
#         df["yds_pergame_off_reg"] = np.nan
#         df["yds_pergame_def_reg"] = np.nan

    df["firstdowns_pergame_off"] = safe_div(fd_off_sum, game_count_data)
    df["firstdowns_pergame_def"] = safe_div(fd_def_sum, game_count_data)
    df['net_firstdowns_pergame'] = df['firstdowns_pergame_off'] - df['firstdowns_pergame_def']

#     if has_game_type and reg_game_count_data is not None:
#         if "season_type" in df_clean.columns:
#             df_clean_reg = df_clean[df_clean["season_type"] == "REG"]
#         else:
#             df_clean_reg = df_clean
#         fd_off_sum_reg = df_clean_reg.groupby("posteam")["first_down"].sum().reindex(teams)
#         fd_def_sum_reg = df_clean_reg.groupby("defteam")["first_down"].sum().reindex(teams)
#         df["firstdowns_pergame_off_reg"] = safe_div(fd_off_sum_reg, reg_game_count_data)
#         df["firstdowns_pergame_def_reg"] = safe_div(fd_def_sum_reg, reg_game_count_data)
#     else:
#         df["firstdowns_pergame_off_reg"] = np.nan
#         df["firstdowns_pergame_def_reg"] = np.nan

    # suffix columns to match your pipeline pattern
    df = df.add_suffix("_thisyear")
    
    
    # difference between this year and post thanksgiving

    return df

### Differences between season-to-date and last season data

In [376]:
def subtract(df):
    df['net_epa_difference'] = df['net_epa_thisyear'] - df['postweek7_net_epa']
    df['net_wpa_difference'] = df['net_wpa_thisyear'] - df['postweek7_net_wpa']
    df['off_epa_difference'] = df['off_epa_thisyear'] - df['postweek7_epa_off']
    df['off_wpa_difference'] = df['off_wpa_thisyear'] - df['postweek7_wpa_off']
    df['def_epa_difference'] = df['def_epa_thisyear'] - df['postweek7_epa_def']
    df['def_wpa_difference'] = df['def_wpa_thisyear'] - df['postweek7_wpa_def']
    df['ypp_difference'] = df['ydsperplay_thisyear'] - df['postweek7_yards_gained']
    df['opp_ypp_difference'] = df['opp_ydsperplay_thisyear'] - df['postweek7_opp_ydsperplay']
    df['ypa_difference'] = df['ydsperattempt_thisyear'] - df['postweek7_ydsperattempt']
    df['opp_ypa_difference'] = df['opp_ydsperattempt_thisyear'] - df['postweek7_opp_ydsperattempt']
    df['ypr_difference'] = df['ydsperrush_thisyear'] - df['postweek7_ydsperrush']
    df['opp_ypr_difference'] = df['opp_ydsperrush_thisyear'] - df['postweek7_opp_ydsperrush']
    df['off_2ndydstogo_difference'] = df['ydstogo_2nd_off_thisyear'] - df['postweek7_2ndydstogo_off']
    df['def_2ndydstogo_difference'] = df['ydstogo_2nd_def_thisyear'] - df['postweek7_2ndydstogo_def']
    df['off_3rdydstogo_difference'] = df['ydstogo_3rd_off_thisyear'] - df['postweek7_3rdydstogo_off']   
    df['def_3rdydstogo_difference'] = df['ydstogo_3rd_def_thisyear'] - df['postweek7_3rdydstogo_def'] 
    df['off_third_converted_difference'] = df['third_down_off_thisyear'] - df['postweek7_3rddownconverted_off']   
    df['def_third_converted_difference'] = df['third_down_def_thisyear'] - df['postweek7_3rddownconverted_def']
    df['off_ppg_difference'] = df['points_pergame_off_thisyear'] - df['postweek7_points_pergame_off'] 
    df['def_ppg_difference'] = df['points_pergame_def_thisyear'] - df['postweek7_points_pergame_def']   
    df['win_pct_difference'] = df['win_percentage_thisyear'] - df['postweek7_win_percentage']    
    df['off_pd_difference'] = df['off_pointdifferential_thisyear'] - df['postweek7_off_pointdifferential'] 
    df['def_pd_difference'] = df['def_pointdifferential_thisyear'] - df['postweek7_def_pointdifferential'] 
    return df


## Construct feature sets for each game

In [377]:
### organization, create a feature set for each game (up till year before current season)


game_list_prev = []
results = []
this_season = fullteamdata_arr.pop(current_year - 2020)
year = 2020
count = 0
count_iter = 0
for fullteamdata in fullteamdata_arr:
#   if count_iter == 1:
#     break
  pbp_thisyear=pbp_data[pbp_data['season']==year]
  pbp_lastyear=pbp_data[pbp_data['season']==year-1]
  pbp_lastyear=pbp_lastyear[pbp_lastyear['season_type'] == 'REG']
  win_totals_temp = win_totals[win_totals['season']==year]
  win_totals_lastyear = win_totals[win_totals['season']==year-1]
  win_totals_lastyear = win_totals_lastyear[win_totals_lastyear['game_type']=='REG']
  week1_df = pd.DataFrame(index=fullteamdata.columns)
  fullteamdata.set_index('team',inplace=True)
#   thanksgiving = fullteamdata.loc[:,'postthxgiving_ydsperplay':'postthxgiving_def_comp_percentage']
  thxgiving_cols = fullteamdata.columns[fullteamdata.columns.str.contains("postthxgiving", case=False, na=False)]
  thanksgiving = fullteamdata.loc[:,thxgiving_cols]

  thanksgiving.columns = thanksgiving.columns.str.replace('postthxgiving_','')
  thanksgiving = thanksgiving.add_suffix('_thisyear')
  for i in range(1, 23, 1):
    df_temp_thisyear = None
    win_totals_temp_thisyear = None
    if i > 1 and i <= 6:
        df_temp_thisyear = pbp_thisyear[pbp_thisyear['week']<i]
        win_totals_temp_thisyear = win_totals_temp[win_totals_temp['week']<i]
    if i <= 6:
      df_temp=pbp_lastyear[pbp_lastyear['week']>(i + 6)]
      win_totals_temp_lastyear = win_totals_lastyear[win_totals_lastyear['week']>(i+6)]
      df_past6weeks=transform(df_temp, df_temp_thisyear)
      
      if i == 1:
        df_thisseason = thisseason(df_temp, win_totals_temp_lastyear)
      else:
        # concat dataframes
        thisseason_first_param = pd.concat([df_temp, df_temp_thisyear, df_temp_thisyear], ignore_index=True)
        thisseason_second_param = pd.concat([win_totals_temp_lastyear, win_totals_temp_thisyear,win_totals_temp_thisyear], ignore_index=True)
        df_thisseason = thisseason(thisseason_first_param, thisseason_second_param)
#         df_thisseason = thanksgiving
        
        
    else:
      df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-6)]
      df_past6weeks=transform(df_temp)
      if i > 11:
        df_lastnine = pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-9)]
        df_totalyear = pbp_thisyear[pbp_thisyear['week']<i]
        win_totals_lastnine = win_totals_temp[(win_totals_temp['week']<i)&(win_totals_temp['week']>=i-9)]
        win_totals_totalyear = win_totals_temp[win_totals_temp['week']<i]
        thisseason_first_param = pd.concat([df_totalyear, df_lastnine], ignore_index=True)
        thisseason_second_param = pd.concat([win_totals_totalyear, win_totals_lastnine], ignore_index=True)

        df_thisseason = thisseason(thisseason_first_param, thisseason_second_param)
      else:
        df_thisseason = thisseason(pbp_thisyear[pbp_thisyear['week']<i],win_totals_temp[win_totals_temp['week']<i])

    df_past6weeks=df_past6weeks.add_suffix('_6weeks')
    
    
    
    if i <= 4:
      df_temp=pbp_lastyear[pbp_lastyear['week']>9+i]
      df_past4weeks=transform(df_temp, df_temp_thisyear)
    else:
      df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-4)]
      df_past4weeks=transform(df_temp)
    df_past4weeks=df_past4weeks.add_suffix('_4weeks')
#     if i <= 2:
#       df_temp=pbp_lastyear[pbp_lastyear['week']>13+i]
#       df_past2weeks=transform(df_temp, df_temp_thisyear)
#     else:
#       df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-2)]
#       df_past2weeks=transform(df_temp)
#     df_past2weeks=df_past2weeks.add_suffix('_2weeks')

    df_thisseason.fillna(0,inplace=True)
    fullteamdata_joined = fullteamdata.join(df_thisseason.join(df_past6weeks.join(df_past4weeks)))

#     fullteamdata_joined = fullteamdata.join(df_thisseason.join(df_past5weeks.join(df_past3weeks.join(df_past2weeks))))
#     thisyear_temp = fullteamdata_joined.loc[:,'ydsperplay_thisyear':'def_comp_percentage_thisyear']
#     thisyear_temp = fullteamdata_joined.iloc[:,215:254]
#     thisyear_temp = thisyear_temp.drop(thisyear_temp.columns[12:20], axis=1)

#     thisyear_temp.columns = thisyear_temp.columns.str.replace('_thisyear','')
#     postthxgiving_temp = fullteamdata_joined.loc[:,'postthxgiving_ydsperplay':'postthxgiving_def_comp_percentage']
#     postthxgiving_temp = fullteamdata_joined.iloc[:,176:207]

#     postthxgiving_temp.columns = postthxgiving_temp.columns.str.replace('postthxgiving_','')
#     subtract = thisyear_temp.subtract(postthxgiving_temp).add_suffix('_difference')
#     fullteamdata_joined = fullteamdata_joined.join(subtract)
    fullteamdata_joined = subtract(fullteamdata_joined)
    
    #make the time list
    # time_week = []
    # for a in range(0,378):
    #   time_week.append(i)
    # time_week

    for j in win_totals_temp[win_totals_temp['week']==i].index:
      away = fullteamdata_joined.loc[win_totals_temp.loc[j, 'away_team']]
      home = fullteamdata_joined.loc[win_totals_temp.loc[j, 'home_team']]
      df_away = pd.DataFrame(fullteamdata_joined.loc[win_totals_temp.loc[j, 'away_team']].add_suffix('_away')).rename(columns={win_totals_temp.loc[j, 'away_team']:'data'})
      df_home = pd.DataFrame(fullteamdata_joined.loc[win_totals_temp.loc[j, 'home_team']].add_suffix('_home')).rename(columns={win_totals_temp.loc[j, 'home_team']:'data'})
      df_difference = pd.DataFrame(away.subtract(home).add_suffix('_difference')).rename(columns={0:'data'})
      df = pd.concat([df_away,pd.concat([df_home,df_difference])])
      df = pd.concat([df, pd.DataFrame([i],index=['week'],columns=['data'])])
      df.fillna(0,inplace=True)
      count += 1

#       if df.isna().sum().sum() > 0:  
#         cols_with_nulls = df.columns[df.isna().any()]
#         print(cols_with_nulls)
#         count_iter += 1



      df_list = list(df['data'])





      results.append([win_totals_temp.loc[j,'away_score'],win_totals_temp.loc[j,'home_score']])
      game_list_prev.append(df_list)
  year+=1
  fullteamdata.reset_index(inplace=True)
    
    
    


fullteamdata_arr.append(this_season)
# team = 'ARI'
# fullteamdata_2021_reset[fullteamdata_2021_reset['team']==team].reset_index()
# fullteamdata_2021.loc[team]
# week1_df =
len(game_list_prev)
# fullteamdata_2021
# game_list_2022
# game_list_2022

1408

In [378]:
this_year_schedule = nfl.import_schedules([current_year])
sundays = pd.to_datetime(this_year_schedule[this_year_schedule['weekday'] == 'Sunday']['gameday']).unique()[:-1]
tuesdays = sundays + pd.Timedelta(days=2, hours=7)
dates_df = pd.DataFrame({'Tuesdays': tuesdays, 'Week': range(1,len(tuesdays)+1)})
today = pd.to_datetime(datetime.today())
dates_df = dates_df[dates_df['Tuesdays'] > today]
current_week = None
if len(dates_df) == 0:
    current_week = int(this_year_schedule.tail(1)['week'])
else:
    current_week = int(dates_df.head(1)['Week'])
    

In [516]:
### create a feature set for each game(2024)
game_list_2024 = []
training_data = []
results_2024 = []
# week1_df = pd.DataFrame(index=this_year.columns)
this_season.set_index('team',inplace=True)
pbp_thisyear=pbp_data[pbp_data['season']==current_year]
pbp_lastyear=pbp_data[pbp_data['season']==current_year-1]
pbp_lastyear=pbp_lastyear[pbp_lastyear['season_type'] == 'REG']

win_totals_temp = win_totals[win_totals['season']==current_year]
win_totals_lastyear = win_totals[win_totals['season']==current_year-1]
win_totals_lastyear = win_totals_lastyear[win_totals_lastyear['game_type']=='REG']
# win_totals_2021[win_totals_2021['week']==1].index
# count_bye = 0
# count_byetwoweeks = 0
# thanksgiving = fullteamdata.loc[:,'postthxgiving_ydsperplay':'postthxgiving_def_comp_percentage']
thxgiving_cols = fullteamdata.columns[fullteamdata.columns.str.contains("postthxgiving", case=False, na=False)]
thanksgiving = fullteamdata.loc[:,thxgiving_cols]

thanksgiving.columns = thanksgiving.columns.str.replace('postthxgiving_','')
thanksgiving = thanksgiving.add_suffix('_thisyear')

###change this value!!!
current_week = 22


####
temp_thisseason = None
temp_past5 = None
temp_df = None
count_iter=0

for i in range(1, current_week+1, 1):
  
  if count_iter == 1:
    break
    
    
  df_temp_thisyear = None
  win_totals_temp_thisyear = None
  if i > 1 and i <= 6:
    df_temp_thisyear = pbp_thisyear[pbp_thisyear['week']<i]  
    win_totals_temp_thisyear = win_totals_temp[win_totals_temp['week']<i]
  if i <= 6:
#     df_thisseason = thanksgiving
    df_temp=pbp_lastyear[pbp_lastyear['week']>(i+6)]
    win_totals_temp_lastyear = win_totals_lastyear[win_totals_lastyear['week']>(i+6)]

    df_past6weeks=transform(df_temp,df_temp_thisyear)
    if i == 1:
        df_thisseason = thisseason(df_temp, win_totals_temp_lastyear)
    else:
        # concat dataframes
        thisseason_first_param = pd.concat([df_temp, df_temp_thisyear, df_temp_thisyear], ignore_index=True)
        thisseason_second_param = pd.concat([win_totals_temp_lastyear, win_totals_temp_thisyear,win_totals_temp_thisyear], ignore_index=True)
        df_thisseason = thisseason(thisseason_first_param, thisseason_second_param)

  else:
    df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-6)]
    df_past6weeks=transform(df_temp)
    if i > 11:
      df_lastnine = pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-9)]
      df_totalyear = pbp_thisyear[pbp_thisyear['week']<i]
      win_totals_lastnine = win_totals_temp[(win_totals_temp['week']<i)&(win_totals_temp['week']>=i-9)]
      win_totals_totalyear = win_totals_temp[win_totals_temp['week']<i]
      thisseason_first_param = pd.concat([df_totalyear, df_lastnine], ignore_index=True)
      thisseason_second_param = pd.concat([win_totals_totalyear, win_totals_lastnine], ignore_index=True)

      df_thisseason = thisseason(thisseason_first_param, thisseason_second_param)
    else:
      df_thisseason = thisseason(pbp_thisyear[pbp_thisyear['week']<i],win_totals_temp[win_totals_temp['week']<i])

  df_past6weeks=df_past6weeks.add_suffix('_6weeks')
  if i <= 4:
    df_temp=pbp_lastyear[pbp_lastyear['week']>9+i]
    df_past4weeks=transform(df_temp,df_temp_thisyear)
  else:
    df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-4)]
    df_past4weeks=transform(df_temp)
  df_past4weeks=df_past4weeks.add_suffix('_4weeks')
#   if i <= 2:
#     df_temp=pbp_lastyear[pbp_lastyear['week']>13+i]
#     df_past2weeks=transform(df_temp,df_temp_thisyear)
#   else:
#     df_temp=pbp_thisyear[(pbp_thisyear['week']<i)&(pbp_thisyear['week']>=i-2)]
#     df_past2weeks=transform(df_temp)
#   df_past2weeks=df_past2weeks.add_suffix('_2weeks')
  # if i == 5:
  #   print(df_thisseason.iloc[:,30:40])
  df_thisseason.fillna(0)
  fullteamdata_joined = this_season.join(df_thisseason.join(df_past6weeks.join(df_past4weeks))) 
#   fullteamdata_joined = this_season.join(df_thisseason.join(df_past5weeks.join(df_past3weeks.join(df_past2weeks))))
#   thisyear_temp = fullteamdata_joined.loc[:,'ydsperplay_thisyear':'def_comp_percentage_thisyear']
#   thisyear_temp = fullteamdata_joined.iloc[:,215:254]
#   thisyear_temp = thisyear_temp.drop(thisyear_temp.columns[12:20], axis=1)
#   thisyear_temp.columns = thisyear_temp.columns.str.replace('_thisyear','')
# #   postthxgiving_temp = fullteamdata_joined.loc[:,'postthxgiving_ydsperplay':'postthxgiving_def_comp_percentage']
#   postthxgiving_temp = fullteamdata_joined.iloc[:,176:207]

#   postthxgiving_temp.columns = postthxgiving_temp.columns.str.replace('postthxgiving_','')
#   subtract = thisyear_temp.subtract(postthxgiving_temp).add_suffix('_difference')
#   fullteamdata_joined = fullteamdata_joined.join(subtract)
  fullteamdata_joined = subtract(fullteamdata_joined)

    
  #make the time list

  for j in win_totals_temp[win_totals_temp['week']==i].index:
    away = fullteamdata_joined.loc[win_totals_temp.loc[j, 'away_team']]
    home = fullteamdata_joined.loc[win_totals_temp.loc[j, 'home_team']]
    df_away = pd.DataFrame(fullteamdata_joined.loc[win_totals_temp.loc[j, 'away_team']].add_suffix('_away')).rename(columns={win_totals_temp.loc[j, 'away_team']:'data'})
    df_home = pd.DataFrame(fullteamdata_joined.loc[win_totals_temp.loc[j, 'home_team']].add_suffix('_home')).rename(columns={win_totals_temp.loc[j, 'home_team']:'data'})
    df_difference = pd.DataFrame(away.subtract(home).add_suffix('_difference')).rename(columns={0:'data'})
    df = pd.concat([df_away,pd.concat([df_home,df_difference])])
    df = pd.concat([df, pd.DataFrame([i],index=['week'],columns=['data'])])
    df_list = list(df['data'])
    if i == 1:
        temp_df = df
        
    df = df.T
    if df.isna().sum().sum() > 0:  
        cols_with_nulls = df.columns[df.isna().any()]
        print(cols_with_nulls)
        count_iter += 1
#         print(df)


    if i == current_week:
      game_list_2024.append(df_list)
    else:
      training_data.append(df_list)
      results_2024.append([win_totals_temp.loc[j,'away_score'],win_totals_temp.loc[j,'home_score']])

this_season.reset_index(inplace=True)


# team = 'ARI'
# fullteamdata_2021_reset[fullteamdata_2021_reset['team']==team].reset_index()
# fullteamdata_2021.loc[team]
# week1_df =

len(game_list_2024)
# fullteamdata_2021
# game_list_2022
# game_list_2022

1

In [507]:
len(game_list_prev[0])

715

In [407]:
df_thisseason.iloc[:,0:20].sort_index()

,off_epa_thisyear,off_wpa_thisyear,def_epa_thisyear,def_wpa_thisyear,net_epa_thisyear,net_wpa_thisyear,offrp_epa_thisyear,offrp_wpa_thisyear,defrp_epa_thisyear,defrp_wpa_thisyear,net_rp_epa_thisyear,net_rp_wpa_thisyear,off4q_epa_thisyear,off4q_wpa_thisyear,def4q_epa_thisyear,def4q_wpa_thisyear,ydstogo_2nd_off_thisyear,ydstogo_2nd_def_thisyear,net_ydstogo_2nd_thisyear,ydstogo_3rd_off_thisyear
team,,,,,,,,,,,,,,,,,,,,
ARI,-0.040745,-0.000705,0.139108,0.004439,-0.179852,-0.005144,-0.042360,-0.001146,0.118047,0.003417,-0.160407,-0.004563,-0.101979,-0.004899,0.098451,0.006004,8.338495,7.159914,-1.178581,7.736655
ATL,-0.000303,0.002446,0.009900,0.001420,-0.010203,0.001026,-0.006238,0.000811,-0.020392,0.000073,0.014155,0.000737,-0.051869,0.003084,-0.005668,0.002265,7.807775,7.905782,0.098006,6.704627
BAL,0.062574,0.002040,0.076535,0.002686,-0.013960,-0.000646,0.045734,0.002564,0.056957,0.002024,-0.011223,0.000539,0.122697,0.003183,0.173157,0.007721,7.544153,7.471338,-0.072815,6.189781
BUF,0.128593,0.004099,0.016984,0.000878,0.111609,0.003221,0.135571,0.003608,-0.029393,-0.000291,0.164964,0.003899,0.117565,0.005668,-0.035923,-0.002182,6.941696,7.819302,0.877606,5.946745
CAR,-0.012968,0.001897,0.086864,0.003514,-0.099831,-0.001617,-0.049785,0.000158,0.072311,0.002384,-0.122096,-0.002226,0.040815,0.004810,0.084362,0.004776,7.608407,7.629412,0.021005,6.893239
CHI,0.092949,0.004004,0.038170,0.002338,0.054779,0.001666,0.087669,0.003532,0.046571,0.002127,0.041098,0.001405,0.193328,0.008154,0.036415,0.002933,7.859083,7.254025,-0.605058,6.264935
CIN,0.061222,0.001181,0.089097,0.003375,-0.027874,-0.002194,0.028158,-0.000077,0.082162,0.003065,-0.054003,-0.003142,0.054509,0.000536,0.167131,0.006011,7.349138,7.539535,0.190397,6.795139
CLE,-0.150998,-0.003340,-0.070659,-0.000803,-0.080339,-0.002537,-0.174118,-0.005178,-0.097905,-0.001339,-0.076213,-0.003839,-0.214580,-0.008223,-0.104208,-0.002067,8.595349,8.046357,-0.548992,8.088816
DAL,0.119426,0.005376,0.189774,0.006747,-0.070348,-0.001371,0.105890,0.004522,0.192090,0.007352,-0.086200,-0.002830,0.083675,0.009111,0.187247,0.009467,7.412371,7.948546,0.536175,6.491039


In [408]:
df_past6weeks

,off_epa_6weeks,off_wpa_6weeks,def_epa_6weeks,def_wpa_6weeks,epa_net_6weeks,wpa_net_6weeks,offrp_epa_6weeks,offrp_wpa_6weeks,defrp_epa_6weeks,defrp_wpa_6weeks,...,ydstogo_3rd_off_6weeks,ydstogo_3rd_def_6weeks,third_down_off_6weeks,third_down_def_6weeks,ydsperplay_6weeks,ydsperattempt_6weeks,ydsperrush_6weeks,opp_ydsperplay_6weeks,opp_ydsperattempt_6weeks,opp_ydsperrush_6weeks
posteam,,,,,,,,,,,,,,,,,,,,,
ARI,-0.005242,-0.000085,0.241146,0.005772,-0.246388,-0.005857,0.003243,0.000244,0.225828,0.004833,...,7.975610,5.264151,0.390244,0.603774,5.276042,5.804688,4.218750,5.934363,6.958042,4.672414
ATL,0.058707,0.006010,-0.054290,-0.001423,0.112997,0.007434,0.040451,0.002435,-0.062495,-0.001765,...,7.603774,6.807693,0.396226,0.403846,5.538153,6.101449,4.837838,5.431535,5.850649,4.689655
BAL,0.189304,0.006392,0.094080,0.004675,0.095224,0.001717,0.217514,0.009348,0.078207,0.004403,...,6.750000,6.431818,0.522727,0.409091,6.735577,7.882353,5.943089,6.156780,7.142857,3.720588
BUF,0.126317,0.004410,0.003349,0.000830,0.122967,0.003581,0.139055,0.004505,-0.041721,0.000132,...,5.906667,6.821918,0.506667,0.438356,5.645669,6.347418,4.755952,5.120370,5.256410,4.914729
CAR,-0.011064,0.000984,0.079265,0.004850,-0.090330,-0.003866,-0.069298,-0.002078,0.055584,0.003531,...,7.303571,7.028986,0.357143,0.492754,4.928839,5.687500,3.461539,5.185759,6.406977,3.794702
CHI,0.120483,0.004659,0.056356,0.004780,0.064128,-0.000121,0.106001,0.004330,0.082340,0.004236,...,5.662651,6.683544,0.433735,0.392405,5.966921,7.102041,4.087838,5.629820,6.489270,4.346154
CIN,0.149165,0.002233,-0.040956,0.003348,0.190121,-0.001115,0.147381,0.001236,-0.095160,0.000446,...,5.772727,8.250000,0.500000,0.277778,5.858333,6.618421,4.545455,5.319018,5.494737,5.073529
CLE,-0.153208,-0.002272,-0.046158,-0.001989,-0.107051,-0.000283,-0.220670,-0.005516,-0.038415,-0.003249,...,8.448979,6.113636,0.367347,0.340909,4.350000,4.891667,3.537500,5.459575,5.552239,5.336634
DAL,0.083081,0.003410,0.271718,0.007187,-0.188637,-0.003777,0.107335,0.003832,0.268885,0.007989,...,6.395833,6.473684,0.333333,0.447368,5.772908,6.808824,4.547826,6.933649,8.362904,4.896552


In [393]:
win_totals_temp[win_totals_temp['week']==current_week-1]

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium,away_win,home_win
7247,2025_18_CAR_TB,2025,REG,18,2026-01-03,Saturday,16:30,CAR,14,TB,...,00-0034855,Bryce Young,Baker Mayfield,Dave Canales,Todd Bowles,Brad Allen,TAM00,Raymond James Stadium,0,1
7248,2025_18_SEA_SF,2025,REG,18,2026-01-03,Saturday,20:00,SEA,13,SF,...,00-0037834,Sam Darnold,Brock Purdy,Mike Macdonald,Kyle Shanahan,Bill Vinovich,SFO01,Levi's Stadium,1,0
7249,2025_18_NO_ATL,2025,REG,18,2026-01-04,Sunday,13:00,NO,17,ATL,...,00-0029604,Tyler Shough,Kirk Cousins,Kellen Moore,Raheem Morris,Ron Torbert,ATL97,Mercedes-Benz Stadium,0,1
7250,2025_18_CLE_CIN,2025,REG,18,2026-01-04,Sunday,13:00,CLE,20,CIN,...,00-0036442,Shedeur Sanders,Joe Burrow,Kevin Stefanski,Zac Taylor,Alex Kemp,CIN00,Paycor Stadium,1,0
7251,2025_18_IND_HOU,2025,REG,18,2026-01-04,Sunday,13:00,IND,30,HOU,...,00-0039163,Riley Leonard,C.J. Stroud,Shane Steichen,DeMeco Ryans,Land Clark,HOU00,NRG Stadium,0,1
7252,2025_18_TEN_JAX,2025,REG,18,2026-01-04,Sunday,13:00,TEN,7,JAX,...,00-0036971,Cam Ward,Trevor Lawrence,Brian Callahan,Liam Coen,Scott Novak,JAX00,TIAA Bank Stadium,0,1
7253,2025_18_GB_MIN,2025,REG,18,2026-01-04,Sunday,13:00,GB,3,MIN,...,00-0039923,Clayton Tune,J.J. McCarthy,Matt LaFleur,Kevin O'Connell,John Hussey,MIN01,U.S. Bank Stadium,0,1
7254,2025_18_DAL_NYG,2025,REG,18,2026-01-04,Sunday,13:00,DAL,17,NYG,...,00-0040691,Dak Prescott,Jaxson Dart,Brian Schottenheimer,Brian Daboll,Adrian Hill,NYC01,MetLife Stadium,0,1
7255,2025_18_NYJ_BUF,2025,REG,18,2026-01-04,Sunday,16:25,NYJ,8,BUF,...,00-0033869,Brady Cook,Mitchell Trubisky,Aaron Glenn,Sean McDermott,Alan Eck,BUF00,New Era Field,0,1
7256,2025_18_DET_CHI,2025,REG,18,2026-01-04,Sunday,16:25,DET,19,CHI,...,00-0039918,Jared Goff,Caleb Williams,Dan Campbell,Ben Johnson,Brad Rogers,CHI98,Soldier Field,1,0


## Creating the model

In [502]:
from sklearn.neural_network import MLPRegressor
from sklearn import model_selection
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


In [503]:

#concatenate past year's data and this year's data
training_x = game_list_prev + training_data
training_y = results + results_2024

training_x = training_x[269:]
training_y = training_y[269:]

# calculate home field
home_advantage = 0
sum_test = 0
for homefield_arr in training_y:
  sum_test += homefield_arr[1] - homefield_arr[0]
home_advantage = sum_test/len(training_y)
home_advantage

2.238532110091743

In [451]:
# prediction_model.predict([game_list_2024[1][238:476] + game_list_2024[1][0:238] + game_list_2024[1][476:]])

array([[19.38573994, 24.4388903 ]])

In [495]:
# # X, y are your full training dataset
# X_train, X_val, y_train, y_val = train_test_split(
#     training_x, training_y, test_size=0.15, random_state=42
# )

# prediction_model = Pipeline([
#       ("scaler", StandardScaler()),
#       ("mlp", MLPRegressor(
#         hidden_layer_sizes=(200, 95, 45),
#         activation='relu',
#         early_stopping=True,
#         max_iter=250,
#         validation_fraction=0.15,
#         n_iter_no_change=40,
#       #         random_state=42,
#       ))
#       ])

# prediction_model.fit(X_train,y_train)
# prediction_model.predict(game_list_2024)

# pred = prediction_model.predict(X_val)
# print(r2_score(y_val, pred))
# print(r2_score(results, prediction_model.predict(game_list_prev)))


-0.042162225755242755
0.10395549935514592


### Monte Carlo-enhanced MLPRegressor

In [520]:
## the model

### create and fit the model

def run_model(training_x, training_y, home_advantage):
    count_epochs = 0
    sum_arr = np.array([])
    r2_list = []
    while count_epochs < 25:

      prediction_model = Pipeline([
      ("scaler", StandardScaler()),
      ("mlp", MLPRegressor(
        hidden_layer_sizes=(200, 95, 45),
        activation='relu',
        early_stopping=True,
        max_iter=250,
        validation_fraction=0.15,
        n_iter_no_change=40,
      #         random_state=42,
      ))
      ])

      prediction_model.fit(training_x,training_y)#185,110,60,  16
      ###validation
      pred = prediction_model.predict(game_list_prev)
      r2score = r2_score(results, pred)
      r2_list.append(r2score)
      # prediction_model.predict([first_game])
      print(r2score)
      # pred
      if r2score >= 0.085 and r2score < 0.30:
          if count_epochs > 0:
            sum_arr = np.array(prediction_model.predict(game_list_2024)) + sum_arr
          else:
            sum_arr = np.array(prediction_model.predict(game_list_2024))
          count_epochs += 1
      time.sleep(0.1)
    
    print('Average r2 score: ', (sum(r2_list) / len(r2_list)))
    ### predictions in table format
    arr = sum_arr/count_epochs
    current_week_schedule = this_year_schedule[this_year_schedule['week'] == current_week]


    df = pd.DataFrame(arr, columns=['away_score', 'home_score'])
    df.insert(0, 'game', win_totals_temp[win_totals_temp['week']==current_week][['game_id']].set_index(df.index))
    current_week_schedule = current_week_schedule.set_index(df.index)
    # check for neutral site games
    for i in range(0, len(df)):
        if current_week_schedule.loc[i,'location'] == 'Neutral':
            df.loc[i,'away_score'] += 1.50
            df.loc[i,'home_score'] -= 1.50

    return df
# ALWAYS remember to include model parameters: early_stopping=True, alpha, validation_fraction, n_iter_no_change, 
# alpha - adds penalty to larger weights
# validation_fraction - fraction of samples used for testing for early_stopping=True
# n_iter_no_change - number of iterations w/o change before early_stopping takes effect
# This prevents overfitting!!!

run_model(training_x, training_y, home_advantage)

0.2007239437222187
0.041718953189607555
0.1702760863049057
0.19252882288654283
0.12871420185232862
0.1630562729416521
0.06464919328962893
0.19433298954841116
0.18170579942715293
0.15200695608400683
0.2005814146833622
0.09563527934528726
0.0038182971882688155
0.10063588838663035
0.09189800771413892
0.21442929754643636
0.14407339641271177
0.23384436572293538
0.10089311807342655
0.043682146043990955
0.23802226290302325
0.11621041393376624
0.027484738467828507
0.059515301071866644
0.14795887612675873
0.19535235674387674
0.23890250593959655
0.22666651914180624
0.21988595943044204
0.16970044322859934
0.1136143388902699
Average r2 score:  0.14427477891101542


,game,away_score,home_score
0,2025_22_SEA_NE,20.149316,21.36515


In [45]:
# run_model(training_x, training_y, home_advantage)

0.1855344156882573
0.10004744828570417
0.28653077956466066
0.10046464780576059
0.14585598866973654
0.08874089376504973
0.15411703732836007
0.23463357576984845
0.17746521239908836
0.22127959854174645
0.2944054698001369
0.21167971784193307
0.245423196091464
0.15695429309647457
0.1574416357638056
0.17980519148626206
0.1537133337623363
0.2031710953020195
0.20577402490917346
0.177273254036669
0.13227332012706
0.2554140141991631
Average r2 score:  0.18490900655612313


,game,away_score,home_score
0,2025_16_LA_SEA,26.611551,26.364896
1,2025_16_PHI_WAS,23.491998,19.582952
2,2025_16_GB_CHI,27.866036,29.803807
3,2025_16_TB_CAR,21.727860,24.265908
4,2025_16_BUF_CLE,27.766270,20.053085
5,2025_16_LAC_DAL,27.093458,32.261286
6,2025_16_CIN_MIA,12.823385,18.062509
7,2025_16_NYJ_NO,12.726805,17.497139
8,2025_16_MIN_NYG,17.309414,18.676762
9,2025_16_KC_TEN,24.916296,17.895954


In [46]:
# run_model(training_x, training_y, home_advantage)

0.29250111560860015
0.17834322785910062
0.20405583928943238
0.2024342392991781
0.23701772465712118
0.1792143139375828
0.1853779185911923
0.20018204489235397
0.24786741934368678
0.10479784426230682
0.2833029191163308
0.22768306786626497
0.25406668242349056
0.16671447309998372
0.23617572027368033
0.07237129342799897
0.25278419897666804
0.24400080009915176
0.2522556393775985
0.20467411341036545
0.1808028123891487
0.20178964718235842
0.23898715267463289
Average r2 score:  0.21075653078514034


,game,away_score,home_score
0,2025_16_LA_SEA,26.383548,26.061361
1,2025_16_PHI_WAS,24.870257,19.821490
2,2025_16_GB_CHI,27.295838,30.384472
3,2025_16_TB_CAR,21.238309,23.895782
4,2025_16_BUF_CLE,27.827375,19.525757
5,2025_16_LAC_DAL,28.336430,33.813394
6,2025_16_CIN_MIA,12.904536,18.648397
7,2025_16_NYJ_NO,13.008814,18.525089
8,2025_16_MIN_NYG,17.549094,19.076931
9,2025_16_KC_TEN,25.960294,17.948920


In [40]:
## validation testing using r2score


# r2score_arr = []
# for i in range(0,20):
#   prediction_model = MLPRegressor(hidden_layer_sizes=(68,34,17), activation='relu', early_stopping=True, max_iter=1000, validation_fraction = 0.12, n_iter_no_change=25, alpha = 0.0005)
#   prediction_model.fit(training_x,training_y)#185,110,60,  16
#   ###validation
#   pred = prediction_model.predict(game_list_prev)
#   r2score = r2_score(results, pred)
#   # prediction_model.predict([first_game])
#   r2score_arr.append(r2score)
#   time.sleep(0.1)
# print(sum(r2score_arr) / len(r2score_arr))

# r2score_arr = []
# for i in range(0,20):
#   prediction_model = MLPRegressor(hidden_layer_sizes=(100,50,25), activation='relu', early_stopping=True, max_iter=1000, validation_fraction = 0.12, n_iter_no_change=25, alpha = 0.0005)
#   prediction_model.fit(training_x,training_y)#185,110,60,  16
#   ###validation
#   pred = prediction_model.predict(game_list_prev)
#   r2score = r2_score(results, pred)
#   # prediction_model.predict([first_game])
#   r2score_arr.append(r2score)
#   time.sleep(0.1)
# print(sum(r2score_arr) / len(r2score_arr))

# r2score_arr = []
# for i in range(0,20):
#   prediction_model = MLPRegressor(hidden_layer_sizes=(150,75,38), activation='relu', early_stopping=True, max_iter=1000, validation_fraction = 0.12, n_iter_no_change=25, alpha = 0.0005)
#   prediction_model.fit(training_x,training_y)#185,110,60,  16
#   ###validation
#   pred = prediction_model.predict(game_list_prev)
#   r2score = r2_score(results, pred)
#   # prediction_model.predict([first_game])
#   r2score_arr.append(r2score)
#   time.sleep(0.1)
# print(sum(r2score_arr) / len(r2score_arr))

# r2score_arr = []
# for i in range(0,20):
#   prediction_model = MLPRegressor(hidden_layer_sizes=(220,110,55), activation='relu', early_stopping=True, max_iter=1000, validation_fraction = 0.12, n_iter_no_change=25, alpha = 0.0005)
#   prediction_model.fit(training_x,training_y)#185,110,60,  16
#   ###validation
#   pred = prediction_model.predict(game_list_prev)
#   r2score = r2_score(results, pred)
#   # prediction_model.predict([first_game])
#   r2score_arr.append(r2score)
#   time.sleep(0.1)
# print(sum(r2score_arr) / len(r2score_arr))


# r2score_arr = []
# for i in range(0,20):
#   prediction_model = MLPRegressor(hidden_layer_sizes=(300,150,75), activation='relu', early_stopping=True, max_iter=1000, validation_fraction = 0.12, n_iter_no_change=25, alpha = 0.0005)
#   prediction_model.fit(training_x,training_y)#185,110,60,  16
#   ###validation
#   pred = prediction_model.predict(game_list_prev)
#   r2score = r2_score(results, pred)
#   # prediction_model.predict([first_game])
#   r2score_arr.append(r2score)
#   time.sleep(0.1)
# print(sum(r2score_arr) / len(r2score_arr))

In [517]:
# import numpy as np
# from xgboost import XGBRegressor
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error

# def make_xgb(seed: int) -> XGBRegressor:
#     """
#     One stochastic XGBoost regressor.
#     Using subsample/colsample + random_state makes each run slightly different.
#     """
#     return XGBRegressor(
#         objective="reg:squarederror",
#         eval_metric="rmse",          # use rmse for early stopping; compute MSE yourself if desired
#         n_estimators=5000,           # many trees + early stopping
#         learning_rate=0.03,
#         max_depth=6,
#         min_child_weight=10,
#         subsample=0.75,              # stochastic -> ensembles benefit
#         colsample_bytree=0.75,
#         colsample_bynode=0.75,
#         reg_lambda=2.0,
#         reg_alpha=0.0,
#         gamma=0.0,
#         tree_method="hist",
#         n_jobs=-1,
#         random_state=seed,

#         # early stopping (constructor form is often most compatible)
#         early_stopping_rounds=50,
#     )

# def monte_carlo_xgb_predict(
#     X_train, y_train, X_val, y_val, X_test,
#     n_models: int = 25, base_seed: int = 0, verbose: bool = False
# ):
#     """
#     Train n_models XGBRegressor models with different seeds.
#     Return averaged predictions on X_test, and optionally per-model predictions.
#     """
#     preds = []
#     models = []
    
#     count_epochs = 0
#     sum_arr = np.array([])
#     r2_list = []

#     for i in range(n_models):
#         seed = base_seed + i
#         model = make_xgb(seed)

#         # Fit with evaluation set for early stopping
#         model.fit(
#             X_train, y_train,
#             eval_set=[(X_val, y_val)],
#             verbose=False
#         )

#         yhat = model.predict(X_test)
#         preds.append(yhat)
#         models.append(model)
        
#         ###validation
#         pred = model.predict(X_val)
#         r2score = r2_score(y_val, pred)
#         r2_list.append(r2score)
#         # prediction_model.predict([first_game])
#         print(r2score)
#         # pred
#         if r2score >= 0.00:
#             if count_epochs > 0:
#                 sum_arr = np.array(model.predict(game_list_2024)) + sum_arr
#             else:
#                 sum_arr = np.array(model.predict(game_list_2024))
#             count_epochs += 1
# #         time.sleep(0.1)

#         if verbose:
#             # best_iteration is available when early stopping is used
#             best_iter = getattr(model, "best_iteration", None)
#             print(f"model {i+1}/{n_models} seed={seed} best_iter={best_iter}")

# #     preds = np.vstack(preds)                 # shape (n_models, n_test)
# #     avg_pred = preds.mean(axis=0)            # shape (n_test,)

# #     return avg_pred, preds, models
    
#     print('Average r2 score: ', (sum(r2_list) / len(r2_list)))
#     ### predictions in table format
#     arr = sum_arr/count_epochs
#     current_week_schedule = this_year_schedule[this_year_schedule['week'] == current_week]


#     df = pd.DataFrame(arr, columns=['away_score', 'home_score'])
#     df.insert(0, 'game', win_totals_temp[win_totals_temp['week']==current_week][['game_id']].set_index(df.index))
#     current_week_schedule = current_week_schedule.set_index(df.index)
#     # check for neutral site games
#     for i in range(0, len(df)):
#         if current_week_schedule.loc[i,'location'] == 'Neutral':
#             df.loc[i,'away_score'] += 1.50
#             df.loc[i,'home_score'] -= 1.50

    
    
#     return preds, models, df



# # X, y are your full training dataset
# X_train, X_val, y_train, y_val = train_test_split(
#     training_x, training_y, test_size=0.15, random_state=42
# )

# # Suppose X_test is your holdout set you want predictions for
# predictions, models, output_df = monte_carlo_xgb_predict(
#     X_train, y_train, X_val, y_val, game_list_2024,
#     n_models=25,
#     base_seed=100,
#     verbose=True
# )

# output_df

0.12270894925033676
model 1/25 seed=100 best_iter=88
0.1239229952730162
model 2/25 seed=101 best_iter=70
0.11126282676348215
model 3/25 seed=102 best_iter=60
0.1195224457181776
model 4/25 seed=103 best_iter=77
0.11640827274012872
model 5/25 seed=104 best_iter=92
0.11276289802556222
model 6/25 seed=105 best_iter=69
0.10608985937516785
model 7/25 seed=106 best_iter=73
0.125208163454952
model 8/25 seed=107 best_iter=94
0.13701343866966698
model 9/25 seed=108 best_iter=172
0.11932355125425637
model 10/25 seed=109 best_iter=86
0.10145674216653144
model 11/25 seed=110 best_iter=54
0.09892204345602518
model 12/25 seed=111 best_iter=89
0.1108532544456815
model 13/25 seed=112 best_iter=70
0.10823318003048138
model 14/25 seed=113 best_iter=81
0.11383322492795467
model 15/25 seed=114 best_iter=149
0.11165523296145874
model 16/25 seed=115 best_iter=86
0.10919600705637827
model 17/25 seed=116 best_iter=83
0.12883823184073528
model 18/25 seed=117 best_iter=79
0.10411769639640411
model 19/25 seed=118

,game,away_score,home_score
0,2025_22_SEA_NE,22.157526,23.245872


In [519]:
# predictions

[array([[20.293648, 24.089115]], dtype=float32),
 array([[19.418663, 26.034033]], dtype=float32),
 array([[19.431292, 24.60695 ]], dtype=float32),
 array([[20.657118, 27.019323]], dtype=float32),
 array([[18.875177, 24.338339]], dtype=float32),
 array([[20.895796, 24.526035]], dtype=float32),
 array([[21.06423, 24.19332]], dtype=float32),
 array([[19.77059 , 25.497608]], dtype=float32),
 array([[18.846527, 24.49467 ]], dtype=float32),
 array([[21.175867, 24.498001]], dtype=float32),
 array([[22.111   , 22.127052]], dtype=float32),
 array([[21.739412, 24.69654 ]], dtype=float32),
 array([[21.164566, 26.506006]], dtype=float32),
 array([[21.524986, 22.933727]], dtype=float32),
 array([[19.993961, 22.928793]], dtype=float32),
 array([[20.853016, 25.708672]], dtype=float32),
 array([[22.983978, 25.16611 ]], dtype=float32),
 array([[20.621359, 24.432425]], dtype=float32),
 array([[19.841219, 24.755035]], dtype=float32),
 array([[20.681425, 24.806702]], dtype=float32),
 array([[22.90378 , 26

In [518]:
# # arr = output_df
# arr = predictions[10]

# current_week_schedule = this_year_schedule[this_year_schedule['week'] == current_week]


# df = pd.DataFrame(arr, columns=['away_score', 'home_score'])
# df.insert(0, 'game', win_totals_temp[win_totals_temp['week']==current_week][['game_id']].set_index(df.index))
# current_week_schedule = current_week_schedule.set_index(df.index)
# # check for neutral site games
# for i in range(0, len(df)):
#     if current_week_schedule.loc[i,'location'] == 'Neutral':
#         df.loc[i,'away_score'] += 1.50
#         df.loc[i,'home_score'] -= 1.50
        
# df

,game,away_score,home_score
0,2025_22_SEA_NE,22.111,22.127052


In [41]:
# sum_homefield = 0
# sum_gamecount = 0
# for i in range(current_year, current_year-5, -1):
#     thisyear_schedule = win_totals[win_totals['season'] == i]
#     if i == current_year:
#         thisyear_schedule = thisyear_schedule[thisyear_schedule['week'] < current_week]
#     sum_homefield += (thisyear_schedule['home_score'] - thisyear_schedule['away_score'])[thisyear_schedule['location'] != 'Neutral'].sum()
#     sum_gamecount += len(thisyear_schedule[thisyear_schedule['location'] != 'Neutral'])

# homefield_advantage = sum_homefield/sum_gamecount

In [42]:

###test
# depth_chart[(depth_chart['week'] == 1)&(depth_chart['club_code']=='TB')]
# depth_chart.iloc[:,20:30]
#multiple years?
# pbp_list = nfl.import_pbp_data([2015,2016,2017,2018,2019,2020,2021,2022])
# depth_chart[(depth_chart['position']=='QB')&(depth_chart['club_code']=='NE')&(depth_chart['week']==22)]
# pbp_list
#rookie case
# seasonal_data[seasonal_data['player_id']==00000]['completions']
# pbp_rp_2021[pbp_rp_2021['pass']==1].groupby('posteam')['epa'].mean()

# postthxgiving_temp['epa/db_diff']
